### ISSUE TITLE
Team 18 - incorrect classpath in jar file

### ISSUE THREAD

**Issue by ringmaster217** [cs340tabyu/cs340Winter2017#1]
The classpath that was provided in the jar file was incorrect. This prevented us from logging into catan correctly. We are marking this as a P2 bug, but we have fixed the classpath so that we can continue testing.

**Comment by StephBrown923** [comment]
Which group are you grading? Team 11 received this issue from you, but I think you meant to send it to Team 16.

**Comment by ringmaster217** [comment]
I tried to tag team 18, but it won't let me. The TAs need to add me as a collaborator here, I think. Also, I think that everybody watching the repo got notified of this issue.

**Comment by irbishop** [comment]
fixed in https://github.com/irbishop/CS340/issues/66, can't close
