### ISSUE TITLE
UI not able to handle many games being listed

### ISSUE THREAD

**Issue by intcreator** [cs340tabyu/cs340Winter2017#102]
If many games are listed, the UI does not scroll but rather compacts all the games together.

<img width="1462" alt="screen shot 2016-10-26 at 2 10 12 pm" src="https://cloud.githubusercontent.com/assets/19642312/19743326/172f99e8-9b86-11e6-9c6c-6b9e76d73a6a.png">

We were unable to reset the server so we're stuck with all these games being listed.

**Comment by smithskyler** [comment]
The UI code is TA stuff.
