### ISSUE TITLE
Started with 6 destination tickets, 3 of them were automatically kept

### ISSUE THREAD

**Issue by opaquejacob** [cs340tabyu/cs340Winter2017#1034]
And one of the tickets that was automatically kept was a duplicate destination. Other player had it

**Comment by opaquejacob** [comment]
And later in the game, I was able to keep Dallas to New York TWICE

**Comment by erikhparkinson** [comment]
Is this the right team?

**Comment by spenc53** [comment]
How do you reproduce this?
