### ISSUE TITLE
Multiple players can choose the same color

### ISSUE THREAD

**Issue by intcreator** [cs340tabyu/cs340Winter2017#104]
Multiple players can choose the same color when they join a game.

<img width="1462" alt="screen shot 2016-10-26 at 2 15 40 pm" src="https://cloud.githubusercontent.com/assets/19642312/19743544/e3c62350-9b86-11e6-8d20-b8413fab4411.png">

<img width="1462" alt="screen shot 2016-10-26 at 2 17 30 pm" src="https://cloud.githubusercontent.com/assets/19642312/19743567/f7c80864-9b86-11e6-9522-2569cc66318d.png">

**Comment by smithskyler** [comment]
Could you explain how you got this bug? I suspect this is a server thing that doesn't keep two people from choosing the same color if they pick them both before the server poller on the second notices a change.

Does this bug inhibit game results at all? It looks inconvenient, but does it keep you from playing, or let you build roads next to the other players?

**Comment by intcreator** [comment]
If two players stay on the pick color screen and pick the same color without clicking "join game" they are both allowed to select it.  They can both click through "join game" without getting any error messages.

If this is allowed, the game can get very confusing.  Which developments belong to which people?  Which chat messages belong to which people?  From a functional perspective the game may work, but the experience is negatively affected.

This can be fixed by not allowing a player to join if they choose a color already chosen by another color.  This ought to be validated by the server but it can be validated on the client as well if the client simply gets a list of players and their colors right before joining a game.

**Comment by smithskyler** [comment]
Ok. That's more reasonable, though still pretty weird that the server wouldn't validate that. I think that this is a P5 for two reasons: It's something that the server really should handle, and it's strictly a UI-related non-game-changing bug.
