### ISSUE TITLE
Team 9 - P2 - cannot add AI players

### ISSUE THREAD

**Issue by tsmith1644** [cs340tabyu/cs340Winter2017#105]
Trying to add AI players to a game, closes the modal and adds no players to the game. Game closes the modal and adds no players to the game. Game stops there.

**Comment by cojoco** [comment]
Hey, is this meant for team 7 or team 9? I'm on team 7, and just tested our client as downloaded from the spreadsheet, and was able to add AI players just fine. If it is team 7, can you add more detail on what happens?

**Comment by UnoriginalElephant** [comment]
The rubric says nothing about adding AIs.
