### ISSUE TITLE
Crashes when all destination cards are drawn

### ISSUE THREAD

**Issue by lkjames** [cs340tabyu/cs340Winter2017#1058]
I drew 23 destination cards and discarded 2.
My opponent drew 2 destination cards and discarded 1.
28 cards were drawn out of 30 total.
I assume when it tried to refill the 3 available cards for the next draw out of only 2 left, it crashed.

**Comment by lkjames** [comment]
Wait, 28 seems impossible. I must have discarded 3. Anyway, it crashed.

**Comment by bexredd** [comment]
When we drew all 30 destination cards and then tried to draw more the player gets stuck in the draw destination cards screen. It wont let them move on because they haven't selected any cards to keep, but there aren't any cards left to accept

**Comment by dereklh4** [comment]
Fixed. Now when a player tries to draw destination cards when there are none left in the deck, they are notified as such and sent back to the game playing table to take a different action.
