### ISSUE TITLE
Discard Modal Funk

### ISSUE THREAD

**Issue by jbskaggs** [cs340tabyu/cs340Winter2017#106]
![image](https://cloud.githubusercontent.com/assets/22157774/19743623/30d30f14-9b87-11e6-8050-2c1f2027a804.png)
The discard modal gives some really funky errors with its numbers (I not really sure how it is being calculated) I have need to 3, I have 3 wheat when I try to discard all of them I can only discard 2 by pressing the up arrow.  Then if you press the down arrow the number will go up to 3 and the total number to discard at the bottom changes to 4/3 and is disabled.

**Comment by melanie38** [comment]
I was incrementing the resource to discard inside the .setResourceDiscardAmount(). Fixed it by incrementing just before calling this method.
