### ISSUE TITLE
Team 9 - P3 - 4 users reached while first player is waiting doesn't start the game

### ISSUE THREAD

**Issue by tsmith1644** [cs340tabyu/cs340Winter2017#108]
If you create a game and join the game with fewer than 4 players. When the fourth player joins only their client is notified to start gameplay, the rest are left waiting.

**Comment by chaserobertson** [comment]
Also there are no AI options to add in the Player Waiting Modal, but clicking the ADD button still closes the modal and takes you to the empty game.

**Comment by Ironslacker** [comment]
I saw this too. Shouldn't this be a P2 issue? It not only affects gameplay, but blocks it
