### ISSUE TITLE
Claim route stole my wilds

### ISSUE THREAD

**Issue by lkjames** [cs340tabyu/cs340Winter2017#1087]
When I claimed a grey route and chose to use green cards, it used my wilds instead.

**Comment by JakeMoney** [comment]
Fixed, not tested.  (see changes in activeState UserCardSelection function.  User will no longer be presented with a color option they have 0 cards of.  If all are 0, wild will be the only option given).

**Comment by dereklh4** [comment]
tested and confirmed.
