### ISSUE TITLE
Claim route didn't use any cards

### ISSUE THREAD

**Issue by lkjames** [cs340tabyu/cs340Winter2017#1090]
When my opponent claimed st louis to pittsburg or portland to san fran (maybe both, they're both green), he had 0 green cards and 6 wilds, but claiming the route did not take any of either card.

**Comment by lkjames** [comment]
Actually, it may have taken his black cards instead, but you have to have at least one wild for it to work. I tried the same thing (0 greens, 1 wild, claim route size 1 using green), and the app crashed.

**Comment by JakeMoney** [comment]
Can you give me any more information on this bug?  Like what were some other steps leading up to the selection of st louis to pittsburg?  At what point in the game were you?  Were there any other bugs/major issues before this one?

**Comment by lkjames** [comment]
We were somewhere in the middle of the game. I don't remember the exact setup, but both players had cards and claimed routes. My opponent, player 1, if he had at least the right number of wild cards and no greens, he could claim green routes either without losing any cards or losing black cards instead (I'm unsure). For myself, player 2, in the same situation when I tried claiming a green route the app crashed. (Maybe it tried to take my black cards but I didn't have enough?)
Hope that helps you reproduce it.

**Comment by JakeMoney** [comment]
We have not been able to recreate this error.  We believe that what happened here was related to the other bugs with claim route that have already been fixed.

**Comment by lkjames** [comment]
Probably. It was similar to some other issues, maybe a more specific case of other ones.
