### ISSUE TITLE
Game State out of sync

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#111]
## Steps taken

We had three people join a game. We each added a settlement. Then we all left the game. When I came back in I placed a road and a settlement. It should have closed the screen, instead it left it open and wouldn't let me click anywhere. I was able to hit the cancel button and continue. However, that button shouldn't even be there

![settlementwierdness](https://cloud.githubusercontent.com/assets/5455419/19743707/8962f9be-9b87-11e6-8a7d-0fe63a838828.png)

**Comment by smithskyler** [comment]
I haven't been able to reproduce this bug. I tried by running all 4 clients on my computer at once using a local server. I'm not sure what you mean when you said that you had three people join a game. Was the 4th player an AI?

**Comment by dansteren** [comment]
@smithskyler The 4th player (Ken) was an AI. The other 3 players were me and my teammates. I think this is the same root issue as #128. Somehow you either aren't reading the state of the game correctly, or the position of settlements, or your can do functions aren't correct.

**Comment by smithskyler** [comment]
Ok. We did seem to have some issues where it was possible for a game state to interfere with road placement. It's been fixed.
