### ISSUE TITLE
Incorrect Can Do Checks

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#128]
I placed a road in the regular play time and could totally place it in the wrong spot.

I'm assuming that your can do operations are still the same as during the setup round even though they shouldn't be. So, I can't place the road next to my settlement...

![roadplacement](https://cloud.githubusercontent.com/assets/5455419/19744239/d29f0260-9b89-11e6-9f9e-8bc3304a39fc.png)

and I can place it just about wherever I want :) including clear over on this 3:1 port muwahahahaha

![detached_road](https://cloud.githubusercontent.com/assets/5455419/19744235/ce81670e-9b89-11e6-82c2-f00e0f8cdc72.png)

That is definitely cheating! :)

**Comment by MCTWalker** [comment]
This is a problem with the mapstate. I'll work on fixing it.

**Comment by MCTWalker** [comment]
I haven't been able to replicate this particular bug. I did improve the mapstate functions to prevent bugs like this from happening again, though.
