### ISSUE TITLE
Chat box is graphically glitched

### ISSUE THREAD

**Issue by tylercr2** [cs340tabyu/cs340Winter2017#134]
When I send a chat message a copy of the map appears inside the chat. The chat still works, it just looks funny.

**Comment by cojoco** [comment]
Can you please attach an image of this? It would be helpful in debugging it.

**Comment by tylercr2** [comment]
![340chatbug](https://cloud.githubusercontent.com/assets/22208668/19749820/65b42bc4-9ba9-11e6-9894-6ea4f17991d1.png)

I've been hearing that this is a bug in the TA code / swing itself, so I'm not sure if this is worth a point deduction or if it can be fixed without editing the provided framework. Sorry I can't really provide more info, ours does this too, and I've heard this from multiple groups. This time it was victory points.
