### ISSUE TITLE
Discard controller doesn't display total

### ISSUE THREAD

**Issue by Redge-Ballard** [cs340tabyu/cs340Winter2017#138]
The discard controller should have a total for how many cards need to be discarded. 
Yours:
<img width="644" alt="screen shot 2016-10-26 at 2 49 14 pm" src="https://cloud.githubusercontent.com/assets/11576966/19744624/8651060e-9b8b-11e6-98b7-6ef9699dfa7a.png">
The TA's:
<img width="644" alt="screen shot 2016-10-26 at 2 49 16 pm" src="https://cloud.githubusercontent.com/assets/11576966/19744626/8664683e-9b8b-11e6-83bf-f309e0978720.png">

**Comment by ringmaster217** [comment]
This technically is never mentioned in the spec. The spec does contain a picture showing the described desired behavior but never mentions it as a requirement.

**Comment by smithskyler** [comment]
"The button displays the current amount the player has set to discard, out of the total needed, and should be disabled except when a player has set the correct amount."

**Comment by ghost** [comment]
Fixed!
