### ISSUE TITLE
Waiting for trade never closes.

### ISSUE THREAD

**Issue by tylercr2** [cs340tabyu/cs340Winter2017#141]
Domestic Trade with AI, the AI refused trade, but the waiting for trade modal never closed.
Re-join closed the modal.

**Comment by cojoco** [comment]
What is supposed to happen here? We can't alter the AI, and it's possible the AI has not been set up to do anything regarding trades.

**Comment by tylercr2** [comment]
Not sure. The AI in message log says it declined the trade so I really dont know

**Comment by mike0256** [comment]
I got this fixed.
