### ISSUE TITLE
Development Cards Issue

### ISSUE THREAD

**Issue by tylercr2** [cs340tabyu/cs340Winter2017#154]
Bought a development card. When I opened the development card menu, I was able to play the only card in there (I should have 2, 1 old, 1 new). Next turn, my development cards were all grayed out with 0's. Relogged, and I had 2 cards not grayed out. Buying cards isn't updating properly, and it was stuck on 0, even after the next turn.

**Comment by cojoco** [comment]
This should be fixed now.
