### ISSUE TITLE
Road building card can be cancelled and used indefinitely

### ISSUE THREAD

**Issue by Redge-Ballard** [cs340tabyu/cs340Winter2017#165]
If you use a road building card, place your first road, then cancel, it leaves the first road and leaves the dev card in your inventory. Basically, this allows you to make all the roads you want for no charge.

**Comment by Redge-Ballard** [comment]
I realized this can be created in several ways. If you cancel the first OR the second move, it will keep your building card. If you build one of your roads on a water tile, it doesn't actually place your road there, but it doesn't count towards using the road. So basically it shouldn't actually give you that option.

<img width="705" alt="screen shot 2016-10-26 at 3 24 46 pm" src="https://cloud.githubusercontent.com/assets/11576966/19745808/9be76fd0-9b90-11e6-9d49-1897e4d56ca5.png">

**Comment by MCTWalker** [comment]
I fixed the being able to build your road on a water tile part.

**Comment by smithskyler** [comment]
I tested this, and confirmed that you can cancel either the first or second road of roadbuilding to be able to keep playing the card over and over.

**Comment by bmarker6** [comment]
Fixed infinite road issue.
