### ISSUE TITLE
Team 18: Register: Make user with invalid username and password

### ISSUE THREAD

**Issue by smithskyler** [cs340tabyu/cs340Winter2017#17]
I can register a user with an invalid username and password (i.e. '!!!!!!!!!!', !@#!@#$). I'll mark this as P4. Valid characters should be alphanumeric, _, or -.

**Comment by irbishop** [comment]
fixed in https://github.com/irbishop/CS340/issues/65.  I guess I'm not a collaborator so I can't close this, but the issue is closed on our repo
