### ISSUE TITLE
Discard makes me discard too many cards.

### ISSUE THREAD

**Issue by jjaywhitaker** [cs340tabyu/cs340Winter2017#171]
1 too many the first time. 2 too many the second time

**Comment by cojoco** [comment]
How many cards did you have total in each case? It should have asked you to discard half your cards (rounded down). So if you had 8 or 9 cards, you should have discarded 4, for example.

**Comment by cojoco** [comment]
I have not been able to reproduce this, it seems like the number of cards to discard is always half the total number of resource cards, rounded down.
