### ISSUE TITLE
Using the soldier card to move the robber to spot with no players to rob doesn't work

### ISSUE THREAD

**Issue by Redge-Ballard** [cs340tabyu/cs340Winter2017#178]
If the hex where you move the robber doesn't have people to rob, it brings up the correct dialogue (rob 0), but then then the robber doesn't move.

Here's the intended place to put him, top left (I am red, so I can't steal from myself)
<img width="702" alt="screen shot 2016-10-26 at 3 37 17 pm" src="https://cloud.githubusercontent.com/assets/11576966/19746141/49390ef4-9b92-11e6-8363-bf1e4f5ab411.png">

After I finished the move, the robber didn't move.
<img width="575" alt="screen shot 2016-10-26 at 3 37 30 pm" src="https://cloud.githubusercontent.com/assets/11576966/19746140/49338f42-9b92-11e6-88ec-ff6aa0d403af.png">

**Comment by ringmaster217** [comment]
I am unable to replicate this bug.
