### ISSUE TITLE
Discard

### ISSUE THREAD

**Issue by sarahkatherine** [cs340tabyu/cs340Winter2017#187]
When I press the test button, a Discard modal appears that does not function correctly.  When I close the modal and press test again, a modal pops up that says, "Waiting for other players to discard" that never exits.

**Comment by kupiakos** [comment]
I changed this to P2 as it's impossible to move the game forward at all when this happens.

**Comment by phhorton** [comment]
Reproduced by Philip.  The discard allows 6 cards at max to be discarded, but does not remove all of the increase arrows for every resource.  This causes problems, since they can still increase the amount after the player hits the max
