### ISSUE TITLE
Turn Tracker

### ISSUE THREAD

**Issue by sarahkatherine** [cs340tabyu/cs340Winter2017#189]
Only one player shows up in the bottom left corner

**Comment by phhorton** [comment]
Reproduced by Philip.  It only shows one player that is called "Beetlejuice" and none of the players in any of the games I tested have that name

**Comment by kupiakos** [comment]
Not just a stylistic error - you can't see any other point information which is simply incorrect behavior, and not just stylistic. Doesn't really matter in the end as long as it's fixed.
