### ISSUE TITLE
Infinite resource ability in bank

### ISSUE THREAD

**Issue by blossom333** [cs340tabyu/cs340Winter2017#202]
Bank has an infinite number of resources (one player had 10 sheep and another player had 12 sheep when there are only supposed to be 19 total sheep in the bank).

**Comment by KendraCodes** [comment]
This is not a bug in the client code; the given server provides the bank with 24 of each resource instead of the correct number given in the game description, 19.

**Comment by garretthoffa** [comment]
oh, sorry my mistake
