### ISSUE TITLE
Maritime Trade

### ISSUE THREAD

**Issue by sarahkatherine** [cs340tabyu/cs340Winter2017#206]
It appears you can maritime trade when you should not be able to, but pressing the Trade button does not trade.  The functionality of the maritime trade controller is not as the functional spec. specifies.

**Comment by phhorton** [comment]
Reproduced by Philip

**Comment by kupiakos** [comment]
Maritime trade also always reports a ratio of 3.

**Comment by johnlarson** [comment]
Fixed
