### ISSUE TITLE
Robber Will Sometimes Move Back To Original Hex After Being Placed

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#219]
After placing the robber, once the game pulls the new version the robber will sometimes be updated to the hex that it was at previous to being moved.

**Comment by tkatuka** [comment]
After I moved the robber to a position, and bought a dev card the robber was moved back to the previous position and the game froze. When I reloaded the game, I played a turn and the robber unexpectedly changed position to another hex.
