### ISSUE TITLE
Team 10 - Cannot play newly created game

### ISSUE THREAD

**Issue by calvinMcM** [cs340tabyu/cs340Winter2017#22]
Fatal - there are no conditions under which a player can play a game of their own creation.

**Comment by kalebo** [comment]
@calvinMcM requesting clarification. Is this due to the absence of AIs in the provided testing client or something else?

**Comment by garretthoffa** [comment]
I believe the bug had to do with AI,

**Comment by kalebo** [comment]
Thanks, the AI issue has already been fix. Marking this one as fixed and duplicate.
