### ISSUE TITLE
Cannot Play Monument Card

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#221]
After clicking on the option to play a monument card, the PlayDevCard view closes, but victory points don't update. If you click again on the PlayDevCard view, it will open and the monument cards will have the same amount that they had previously. In effect, it does nothing.

**Comment by Chroniclerz** [comment]
The specification indicates that monument cards shouldn't be abled to be played unless the player has sufficient monument cards in hand to win.
https://students.cs.byu.edu/~cs340ta/fall2016/group_project/Web_API_Documentation.pdf
preconditions for monument.
In the situation do you have enough monuments to win?
