### ISSUE TITLE
Game Doesn't Support Multiple Clients

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#223]
When running multiple user clients on the server, both clients will show the color and status of the first player to log in (If I open two clients and log in as Sam first and Brooke second, the game will update to show Sam's information). This also causes the game to be unplayable after the first player has placed a settlement and a road.

**Comment by chaserobertson** [comment]
How can we replicate this error? I can't find any situation where the game is caused to be unplayable after the first placement.

**Comment by wfearn** [comment]
Did you open more than one client and log them into the same game?

**Comment by chaserobertson** [comment]
Yes. "the game will update to show Sam's information" as in brooke's client shows sam's information?

**Comment by wfearn** [comment]
Yeah it shows Sam's color and has his state of the game, so if it's Sam's
turn it will tell Brooke it's her turn as well. Or at least it allows them
both to place settlements at the same time at the beginning.

**Comment by wfearn** [comment]
Make sure you have the clients open at the same time.

**Comment by chaserobertson** [comment]
Got it. Thanks
