### ISSUE TITLE
4:1 brick-wheat simply robs player of 4 brick.

### ISSUE THREAD

**Issue by mhnsn** [cs340tabyu/cs340Winter2017#225]
It is impossible to trade 4 brick for 1 wheat. The brick is removed from inventory, but wheat is never received. However, 3:1 brick-wheat works fine.

**Comment by mhnsn** [comment]
Given that wheat is necessary for building settlements, I'm actually going to label this as P2, since being unable to trade for wheat essentially makes it impossible to continue the game.

For example: took me half an hour just to steal the wheat I needed to build a settlement, then upgrade it.

**Comment by mhnsn** [comment]
Also applies to 4:1 wood-sheep

**Comment by cgrange** [comment]
Seeing as you you continued to play for quite some time this definitely did not block gameplay. Did it affect it? Certainly... But it definitely did not block it

**Comment by cgrange** [comment]
![screenshot 30](https://cloud.githubusercontent.com/assets/16614340/19795430/85ceca64-9c98-11e6-81a5-c88d4825e3f0.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/16614340/19795428/85cb5bae-9c98-11e6-8634-23c63c3e6a1d.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/16614340/19795429/85ce7d7a-9c98-11e6-87b4-f34395422442.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/16614340/19795431/85cf0150-9c98-11e6-8dac-d6e5366113f4.png)

**Comment by cgrange** [comment]
Furthermore, I just tested the zip that we sent and it appears that the maritime trade 4:1 functionality is working swimmingly for both the combinations you suggested. Therefore, I mark this as invalid
