### ISSUE TITLE
Domestic Trade Button is available to be pushed even when it's not your turn.

### ISSUE THREAD

**Issue by jasonmck** [cs340tabyu/cs340Winter2017#228]
The rules state that only the person who owns the turn can initiate a trade. Therefore, when it isn't your client's turn the 'Domestic Trade Button' shouldn't be available to access. This is more of a style bug since when you click the button it says it's not your turn, but I would prefer to not be allowed to think I can initiate a trade.

**Comment by wiseman5** [comment]
The functional specs on page 20 say that is how it is supposed to work.
