### ISSUE TITLE
Attempting to play a city freezes the client.

### ISSUE THREAD

**Issue by mhnsn** [cs340tabyu/cs340Winter2017#229]
Cities cannot be played, though they indicate they can. The client freezes upon trying. Closing and rejoining is only solution.

**Comment by mhnsn** [comment]
Possibly related to #225, as I haven't been able to reproduce it in a game that doesn't have negative resource counts.

**Comment by csydvs** [comment]
Yeah, I can't reproduce this. Here's a city that's been built:
![image](https://cloud.githubusercontent.com/assets/15003465/19791563/57060648-9c7f-11e6-9dc8-076cfcfa79e1.png)
