### ISSUE TITLE
3:1 trade => infinite ore, brick, wool, wheat, and lumber

### ISSUE THREAD

**Issue by mhnsn** [cs340tabyu/cs340Winter2017#231]
This trade cycles through incrementing the brick count until it reaches 3, then returning it to zero, and repeating. Each trade is valid, and the amount of ore is always incremented. This does not appear to affect 2:1 (at least, for ore).

**Comment by daviscodesbugs** [comment]
I can't replicate this issue

**Comment by mhnsn** [comment]
Possibly related to #225, as I haven't been able to replicate it in a game that doesn't have negative resource counts.

**Comment by cgrange** [comment]
I too have gone through done a 3:1 trade of brick to ore and was not able to get infinite amounts of everything. The overlay did not look as it should when I pulled it up again (see #83) but while it may have looked like you could continue to get resources after the initial trade this was not the case.
