### ISSUE TITLE
DevCard Abuse without having an actual dev card

### ISSUE THREAD

**Issue by bvance800** [cs340tabyu/cs340Winter2017#233]
I was able to use any of the dev cards without having them

**Comment by AngelSassin** [comment]
This is what was possible by abusing BuildRoad

<img width="979" alt="screen shot 2016-10-26 at 6 07 06 pm" src="https://cloud.githubusercontent.com/assets/1124200/19749578/4808f462-9ba7-11e6-9b54-1acc3035118d.png">

**Comment by kupiakos** [comment]
Beautiful. Fixed.
