### ISSUE TITLE
No place to build road, stuck forever in build road screen

### ISSUE THREAD

**Issue by bvance800** [cs340tabyu/cs340Winter2017#234]
After abusing the 'longest road' dev card and building infinite roads, I was stuck once there was no room to build them any more.

**Comment by kupiakos** [comment]
Note for implementation: this was put in a todo but was not implemented in `MapController.playRoadBuildingCard`. Maybe the cancel option should have been kept `true`. 😛

Also, this only applies for the Road Building card. Building a road normally should not have this problem, as the action can simply be cancelled.

**Comment by kupiakos** [comment]
Now the only non-cancellable action is the building at the beginning.
