### ISSUE TITLE
Can't build road next to another road (Sometimes) even if road is yours

### ISSUE THREAD

**Issue by bvance800** [cs340tabyu/cs340Winter2017#235]

**Comment by AngelSassin** [comment]
These were the only locations I could build my roads. Every other location I tried to build gave me the invalid symbol.

<img width="979" alt="screen shot 2016-10-26 at 6 07 06 pm" src="https://cloud.githubusercontent.com/assets/1124200/19749596/6d5b7564-9ba7-11e6-81fd-696741fae70d.png">

**Comment by AngelSassin** [comment]
This applies to settlements too.

When road even connects with another player settlement or road, it's considered invalid

<img width="823" alt="screen shot 2016-10-26 at 6 28 35 pm" src="https://cloud.githubusercontent.com/assets/1124200/19749905/2ec4fdcc-9baa-11e6-8006-52b8d2b1adc1.png">
