### ISSUE TITLE
can place settlement on water

### ISSUE THREAD

**Issue by parkji03** [cs340tabyu/cs340Winter2017#237]
placing the settlement on water in the first round breaks the game

**Comment by AngelSassin** [comment]
Selecting this spot on the right...

<img width="825" alt="screen shot 2016-10-26 at 6 22 20 pm" src="https://cloud.githubusercontent.com/assets/1124200/19749821/69cc204a-9ba9-11e6-9355-ef05736784f3.png">

...breaks the game. The build road window does not pop up, and gameplay is blocked.

<img width="994" alt="screen shot 2016-10-26 at 6 22 49 pm" src="https://cloud.githubusercontent.com/assets/1124200/19749818/5b5e3476-9ba9-11e6-864c-8d960fdb0377.png">

**Comment by kupiakos** [comment]
Well that definitely sucks. It definitely screws up the flow of the game, but only if something nonstandard was done (granted it shouldn't have been possible to do). Would that be qualified as a P2 or P3?

**Comment by kupiakos** [comment]
Also fixed. Side note - how is your map rendering so non-crappily?
