### ISSUE TITLE
Sending 'exit' in chat forces close of connection

### ISSUE THREAD

**Issue by mhnsn** [cs340tabyu/cs340Winter2017#249]
This could be related to #231, but it's hard to say, as I've only made this happen once. In a game after abusing the 3:1 glitch, I sent just the word 'exit' in the chat pane.

My server soon registered a force-close of the remote connection.

I continued playing for a bit, then closed the connection, and the chat window began displaying a recursing view on itself.

Upon rejoining the game:
- there is no map display
- the only commands available are trade, buying a dev card, or playing a dev card
- Chat is disabled.
- There is no game history.
- I have all of my (hacked) resources.
- All players are absent from the game's view in the bottom-left, myself included.
- If I have any valid dev cards, I can play an infinite number of them, and the count goes negative for Monument cards. 

It is impossible to win, and it's safe to assume that all game data is either lost or corrupted.

![catan-glitch](https://cloud.githubusercontent.com/assets/3672342/19749653/e9ef6aea-9ba7-11e6-9531-405249aeb666.png)

**Comment by mhnsn** [comment]
There is a trade ratio "-1" that the server logs in the corrupted game file. I believe that getting this bug to work, then closing the connection via chat, then playing more, is the cause.

That said, I have yet to reproduce this issue.

**Comment by mhnsn** [comment]
I'm not sure what to label this as, so can a TA look at this and make the call? We're all a bit unsure as to what to label this as, since thus far it's been un-reproduceable, even though it is fatal.

**Comment by mhnsn** [comment]
Also, as an update: it appears that spamming the server with _anything_ will cause it to close the connection and then increment the port number on the remote.

**Comment by skunkworker** [comment]
This is invalid as the server is not our problem. And we cannot reproduce this issue.

**Comment by mhnsn** [comment]
Reproduceability I understand; I haven't been able to make this happen a second time either.

However, the initial problem here is definitely _not_ the server - our client does not have this issue no matter how much I spam the server or what I send as input - something in your client is causing the server to arbitrarily disconnect. If you aren't doing sanitization of your chat inputs, that would be a good place to look.

**Comment by csydvs** [comment]
@mhnsn I understand what you're saying, however, we're definitely meeting the pre-conditions on the server--we're supposed to be able to send anything to it. I'm glad that you guys made a more watertight input, however, we feel like it's a server thing because we're doing everything that the server preconditions ask of us. Also, I'm going to remove the TA-NotFixed label, as I believe that means that this is a bug that the TAs have looked at and decided we haven't fixed.
