### ISSUE TITLE
Game halts after placing my first settlement and road during setup

### ISSUE THREAD

**Issue by spencerolsen** [cs340tabyu/cs340Winter2017#25]
Steps to reproduce:
1. Login as Sam
2. Create a game
3. Join the newly created game
4. Place a settlement, then a road
5. Game play halts

**Comment by tylercr2** [comment]
Are you sure about this? I cannot reproduce this error, and it strikes me as strange that you are able to place a settlement and a road in a game by yourself, as you shouldn't be able to get past the player waiting controller. You also should not be able to progress until you build a settlement and a road with the other players.

**Comment by spencerolsen** [comment]
Closing:

I had two things wrong with what I submitted. This bug was produced when I joined Game #2, not when I created a new game. I think as I produced this bug I forgot that Game #2 is not full of AI players, which is why game play halted. Nice catch!
