### ISSUE TITLE
Robbing displays option to rob self

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#251]
Robbing displays option to rob self
![bug8](https://cloud.githubusercontent.com/assets/22157895/19749674/0d45fd1a-9ba8-11e6-99d0-cb91c58c9f77.png)

**Comment by UnoriginalElephant** [comment]
duplicate of #263 ?

**Comment by Chroniclerz** [comment]
Different. In this case the robber was placed next to his own settlement, and opened option to rob himself. In the other #263 the Robber was adjacent to no settlements/cities and still opened up a window. I forget the details, but it might have been the last Robber's options.
