### ISSUE TITLE
Turn tracker color off

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#258]
Turn Tracker color not updated currently when player color changed
![bug13](https://cloud.githubusercontent.com/assets/22157895/19749745/b4019060-9ba8-11e6-8084-d01a01acbada.png)

**Comment by UnoriginalElephant** [comment]
duplicate of #255

**Comment by Chroniclerz** [comment]
Similar, and possibly in reference to the same core issue, but its specifically referring to the Turn tracker being multi-colored as per the bottom left corner.
