### ISSUE TITLE
Always opens potential rob targets even if there shouldn't exist any

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#263]
Placing robber on unoccupied hex still prompted player to rob other players. This rob was later rejected by server (no resources transferred)
![bug17](https://cloud.githubusercontent.com/assets/22157895/19749788/34f23472-9ba9-11e6-9d08-cbeac0f2cadc.png)

**Comment by HawkoftheDawn** [comment]
Was this placing the robber a second time (different bug) after you robbed a location with c and a?

**Comment by Chroniclerz** [comment]
I forget which turn this was, but it was the first time I had placed the robber that turn. Not the first time in the game though. I didn't confirm, but I suspect that the robber modal displayed is the old modal from the last time I robbed.

**Comment by HawkoftheDawn** [comment]
Okay, I was just able to replicate it... thanks.
