### ISSUE TITLE
Winning game nonfunctional

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#264]
Winning the game does not display a "game won" screen, nor does it lock out interface (though the server will refuse to accept end turn)
![bug18](https://cloud.githubusercontent.com/assets/22157895/19749808/5195878c-9ba9-11e6-9506-86948dd194fc.png)

**Comment by UnoriginalElephant** [comment]
duplicate with #180 ?

**Comment by Chroniclerz** [comment]
Appears to be. We did not collaborate when writing bugs so there may be duplicates. Feel free to close your least favorite.
