### ISSUE TITLE
Multi color select

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#269]
Players may select same color to play if all log in simultaneously, then 1 by 1 enter the game. All players could be the same color theoretically. Same can be done rejoining.
![bug20](https://cloud.githubusercontent.com/assets/22157895/19749844/a2ddf890-9ba9-11e6-91e2-8ecaf207ffd1.png)

**Comment by UnoriginalElephant** [comment]
possibly p4 or p5

**Comment by thejlyons** [comment]
You can do this in the demo too... Because of the way they designed this project, this can't really be avoided.
