### ISSUE TITLE
When buying a dev card, no card is given sometimes

### ISSUE THREAD

**Issue by Napper15** [cs340tabyu/cs340Winter2017#278]
I believe this is related to the robber card being played twice when played.  I purchased a dev card that was a robber, played the robber.  Then I bought another dev card and it was showing that I did not have any dev card.  This could have been because my robber count was -1 and when I bought another one it brought that up to 0.  But it could have been something else so I am making a new issue.

**Comment by csydvs** [comment]
The ResourceBar cannot display negative numbers, so if you have negative numbers of dev cards, then it will show that you have 0 until you have 0.
