### ISSUE TITLE
Player rolls twice every turn

### ISSUE THREAD

**Issue by wiseman5** [cs340tabyu/cs340Winter2017#279]
Each time it is my turn it has me roll twice before I can do anything else, and the modal is also flashing and hard to click.
![image](https://cloud.githubusercontent.com/assets/16614336/19750066/6358cdb0-9bab-11e6-8d2f-0b351027912f.png)

**Comment by dansteren** [comment]
Let's not deal with the modals flickering here. This issues was also reported in #290. We'll just deal with rolling the dice twice for this issue.
