### ISSUE TITLE
Team 12 - user can't register

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#280]
I tried to register with the username "Adam" and the password "adam" and an error window appeared reporting invalid field errors

**Comment by dansteren** [comment]
From the functional spec (emphasis added):

> Registering a new user should reject the registration if the username is fewer than 3 or greater than
> seven characters, if the password is **less than 5 characters long** or is not made of allowed characters
> (alphanumerics, underscores, hyphens, or if the password verification entry doesn’t match the original.

So, this registration should be rejected because the password "adam" is less than 5 characters.
