### ISSUE TITLE
After rolling a 7 robber window appeard blank and froze

### ISSUE THREAD

**Issue by Napper15** [cs340tabyu/cs340Winter2017#285]
This only happened once.  Don't know what the state was but when I rolled a 7 the rob modal popped up empty.  The console showed a nullPointerExeption 

```
 [java] Exception in thread "Timer-2" java.lang.NullPointerException
 [java]     at client.roll.RollController$1.run(RollController.java:92)
 [java]     at java.util.TimerThread.mainLoop(Timer.java:555)
 [java]     at java.util.TimerThread.run(Timer.java:505)
```

<img width="1354" alt="screen shot 2016-10-26 at 6 51 40 pm" src="https://cloud.githubusercontent.com/assets/11565537/19750319/80895c54-9bad-11e6-93d9-ce5dbe355b19.png">

**Comment by rgavinc** [comment]
We can't reproduce this issue.
