### ISSUE TITLE
After winning a game, cannot start a new game

### ISSUE THREAD

**Issue by Napper15** [cs340tabyu/cs340Winter2017#287]
After winning a game, you pop back up the join game modal which is correct, but then when you join another game it just changes your color on the game you just won instead of actually putting you in the game you were trying to join

**Comment by csydvs** [comment]
I've gotten this to work many times. Sometimes it takes a second to reload the Map GUI, but we didn't write the GUI. This is after joining a new game, after a game ends:
![image](https://cloud.githubusercontent.com/assets/15003465/19791035/c481a48e-9c7a-11e6-9cd5-4b519b096a3c.png)
