### ISSUE TITLE
User can build road past opposing player's settlement.

### ISSUE THREAD

**Issue by mclements37** [cs340tabyu/cs340Winter2017#296]
![screen shot 2016-10-26 at 7 23 04 pm](https://cloud.githubusercontent.com/assets/21322207/19750836/e3a5f456-9bb1-11e6-90fd-2a389b973af4.png)

**Comment by intcreator** [comment]
This issue is considered invalid unless an explicit clarification can be found in the [provided rulebook](https://students.cs.byu.edu/~cs340ta/fall2016/group_project/Catan_Rules.pdf).
