### ISSUE TITLE
Game pauses indefinitely after player clicks "finish turn" button

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#298]
After the player has rolled and clicked "finish turn" the game pauses indefinitely.  It says "waiting for other players" but does not respond.

Refer to the screenshot (especially the game history area)

![screen shot 2016-10-26 at 7 27 10 pm](https://cloud.githubusercontent.com/assets/16737040/19750895/5d118684-9bb2-11e6-82ce-fcea68493fdc.png)

**Comment by dansteren** [comment]
In the screenshot you can see that Sam had to roll twice. I wonder if this caused the game to get out of sync.

**Comment by dansteren** [comment]
I don't think this is specific enough to reproduce. I've been testing it out and haven't been able to make this happen. If anyone can get this to happen again, please document it here
