### ISSUE TITLE
Team 9 - P3 - After having to discard, the robber modal doesn't show up

### ISSUE THREAD

**Issue by tsmith1644** [cs340tabyu/cs340Winter2017#300]
A player rolled a 7 and the same player had to discard. After discarding, the robber modal didn't come up and the game was stuck. Logging out and back allowed game play to continue.

**Comment by Entelechial** [comment]
Happens if another player discarded their cards first.

**Comment by Entelechial** [comment]
Duplicate of #261

**Comment by HawkoftheDawn** [comment]
Duplicate of #262 and #179
