### ISSUE TITLE
Player is allowed to build more than the limit of roads

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#302]
![screen shot 2016-10-26 at 7 43 28 pm](https://cloud.githubusercontent.com/assets/16737040/19751215/e526e74c-9bb4-11e6-82bc-89e3a5a8ef2c.png)

**Comment by intcreator** [comment]
Part of this issue should be checking that the player has enough resources to build roads as well.

**Comment by dansteren** [comment]
@intcreator when you're updating these checks, you should probably add in a check to see if it's the player's turn. I just build a road when it was someone else's turn
