### ISSUE TITLE
Build road modal shows that player can build road in the ocean

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#305]
When a user tries to hover a road over the ocean the program shows that the user can build instead of displaying an x.  The user however is not actually allowed to build the road.

![screen shot 2016-10-26 at 7 38 51 pm](https://cloud.githubusercontent.com/assets/16737040/19751330/9de66bf4-9bb5-11e6-8315-d5d2c6554178.png)

**Comment by intcreator** [comment]
@lastmjs I think this is yours because it has to do with a can do method, but it might belong to @Redge-Ballard instead.
