### ISSUE TITLE
Domestic trade with AI hangs on the "Waiting" screen (Group 5, P2, Phase 2)

### ISSUE THREAD

**Issue by johnlarson** [cs340tabyu/cs340Winter2017#309]
Right after requesting a trade with an AI player, it showed the "Waiting for Trade to Go Through" overlay, and the overlay never went away.

Steps to reproduce:
1. Create a game (mine was with the default game setup, no randomizing.)
2. Enter the game.
3. Add three AI players.
4. Open up the Domestic Trade Dialog
5. Specify a legal trade.
6. Select a player
7. Click "Trade!"

At this point, the "waiting" overlay will come up, and it will stay there until you close the game.

**Comment by xandroxygen** [comment]
Able to reproduce - AI declines trade but game never updates to close modal

**Comment by xandroxygen** [comment]
Update method just didn't recognize the trade fast enough, fixed.
