### ISSUE TITLE
Game does not respond after discarding

### ISSUE THREAD

**Issue by StephBrown923** [cs340tabyu/cs340Winter2017#316]
The regular gameplay didn't start back up again when I was forced to discard on an 8.  The map disappears as well.

![](https://cloud.githubusercontent.com/assets/16614336/19754126/e7945e8e-9bc7-11e6-887d-440daabd7dc7.png)

**Comment by intcreator** [comment]
This is likely related to whatever is causing the freeze on #298.

**Comment by intcreator** [comment]
This has now been isolated to not responding after robbing.
