### ISSUE TITLE
Discard Too Many/Negative Amounts

### ISSUE THREAD

**Issue by michaelpratt28** [cs340tabyu/cs340Winter2017#320]
When the discard resources modal shows, it allows you to select more resources than you have in your resource bank and some go negative as well.
<img width="1009" alt="screen shot 2016-10-26 at 8 21 46 pm" src="https://cloud.githubusercontent.com/assets/15473604/19752355/dc44e7a0-9bb9-11e6-946e-1d52ad64d796.png">

**Comment by garretthoffa** [comment]
I would consider this part of all of the other discard functionality problems we had wouldn't you
