### ISSUE TITLE
Games list not populating

### ISSUE THREAD

**Issue by StephBrown923** [cs340tabyu/cs340Winter2017#33]
Unable to join a game and begin play (the game list never populates, even when you create a new game)

**Comment by SierraD012** [comment]
I'm on @StephBrown923 's team, and I had the same issue with the GameListView. I can see from the server output that a Create Game request is being received, but the view doesn't show the list of games. We had this same issue with our code a while back - one thing you can try is having the view close and reopen right afterwards as soon as a new game is added to the list. This will make sure it refreshes with the new content.

**Comment by SierraD012** [comment]
sorry didn't mean to close this issue

**Comment by dansteren** [comment]
I'm running our original code with `ant run-client` (aka not from the jar) and it's working fine. SO, we must have packaged it wrong. We'll be looking into this right after class. I'll re-post here when we get it fixed and probably send out an email as well.

**Comment by dansteren** [comment]
**Status Update:** We probably won't have this working till 4 just so you're aware. We'll let you know if something happens sooner

**Comment by dansteren** [comment]
I believe this has been resolved with the correctly repackaged jar
