### ISSUE TITLE
Domestic Trade not working

### ISSUE THREAD

**Issue by michaelpratt28** [cs340tabyu/cs340Winter2017#333]
Domestic trade doesn't follow through with trading after you select send/receive and who you want to trade with. It also allows you to select a send amount greater than what you have in your resource bank.
<img width="668" alt="screen shot 2016-10-26 at 8 42 50 pm" src="https://cloud.githubusercontent.com/assets/15473604/19752781/0f06449c-9bbd-11e6-917d-0556362e0e79.png">

**Comment by garretthoffa** [comment]
see 455
