### ISSUE TITLE
Game frozen

### ISSUE THREAD

**Issue by michaelpratt28** [cs340tabyu/cs340Winter2017#334]
Game freezes after domestic trade modal closes. I cannot end my turn. The game throws this exception: 
<img width="712" alt="screen shot 2016-10-26 at 8 47 12 pm" src="https://cloud.githubusercontent.com/assets/15473604/19752834/760f7f5a-9bbd-11e6-893d-6b2662aaf33d.png">

**Comment by garretthoffa** [comment]
see issue 455
