### ISSUE TITLE
Multiple players can build simultaneously during setup

### ISSUE THREAD

**Issue by wiseman5** [cs340tabyu/cs340Winter2017#335]
## Main Issue

Players can build things at the same time during initial setup (they should have to wait for other players).
## Other Issues

_The following information is for reference, as it has been duplicated by other issues._

When two players are playing they were both asked to place a road at the same time.  Also it allowed me to place the road on the ocean which closed the modal but didn't place the road.  Then when the first player placed the road and settlement and finished their turn it did not allow the second player to place a road and settlement.  The game is frozen and can't move forward. 

![image](https://cloud.githubusercontent.com/assets/16614336/19752747/e54ce6ce-9bbc-11e6-902b-9a687e19c022.png)

By logging out and back in I could get it to pop up again and move game play along, but player one was able to place a second road and settlement before player 2

![image](https://cloud.githubusercontent.com/assets/16614336/19752817/542fa680-9bbd-11e6-915f-c7b6b475f37b.png)

**Comment by intcreator** [comment]
There are several issues addressed in the original paragraph.  The can place road preview is addressed in #305.  The game freezing after set up is addressed in #427.  The remaining issue here is that during setup multiple players can build things at the same time.
