### ISSUE TITLE
[Group 14] [P3] Soldiers don't work as outlined in the Spec.

### ISSUE THREAD

**Issue by janderson11** [cs340tabyu/cs340Winter2017#336]
When you play a soldier, you can move the robber visually. However, it doesn't let you steal, and at the end of your turn the robber will move back to the desert. It doesn't decrease the amount of soldiers you have in your hand and the number of soldiers played doesn't increase.

**Comment by daviscodesbugs** [comment]
This bug is a symptom of the fact that we did not implement the robber (issue #349). Since there is an existing issue for this, we'll mark as duplicate and close.
