### ISSUE TITLE
[P2] [Team 5] [Phase 2] Building Settlement Should Be Cancelable

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#338]
When a player has sufficient resources to build a settlement, the Resource Bar allows them to pull up the Build Settlement modal.  However, if there are no vertices where a player can actually place the settlement, they get stuck in that modal because the cancel but was never enabled.

**Comment by xandroxygen** [comment]
Unable to reproduce - every time I have bought a settlement, the cancel button is enabled, see screenshot.
![image](https://cloud.githubusercontent.com/assets/20050280/19774659/19c291d8-9c2b-11e6-843e-a56ce6862a70.png)

**Comment by dannya951** [comment]
I played through a few rounds and was not able to reproduce this either.  For the time being, let's leave it as "Invalid".
