### ISSUE TITLE
Cannot buy DevCard - Game frozen

### ISSUE THREAD

**Issue by michaelpratt28** [cs340tabyu/cs340Winter2017#350]
The game freezes after trying to buy a development card and stays in the DevCardState.
<img width="701" alt="screen shot 2016-10-26 at 8 57 08 pm" src="https://cloud.githubusercontent.com/assets/15473604/19753066/3b15e432-9bbf-11e6-8538-c6b6778187a3.png">

**Comment by garretthoffa** [comment]
see 400
