### ISSUE TITLE
Maritime trade for same resources

### ISSUE THREAD

**Issue by daviscodesbugs** [cs340tabyu/cs340Winter2017#37]
A user can make a maritime trade for the same resource.

Though this is not explicitly prohibited, it might be worth preventing it to avoid user error. However, I realized that a user might want to do it in order to narrow down their cards as "robber proofing" without having to discard half their hand. 

This might not even need fixing.

**Comment by cgrange** [comment]
This feature is allowed for either being clever (such as the robber proofing you mentioned or any other clever reason a client can think of) or to hasten natural selection. Also the t.a.'s demo client has the same behavior so I am going to mark this as invalid
