### ISSUE TITLE
[P3] [Team 5] [Phase 2] Can Rob and Discard the Same Resource

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#371]
The Robbing modal displays on the screen of a person who rolls a 7 every time someone discards who shouldn't have had to have discarded (detailed in another issue).  When the robber is moved, it takes away 1 resource from whomever the player chooses.  However, the discard view is not updated to reflect this (nor should it be, since robbing should never happen until all discarding is complete), so the max discard limit for a resource in the discard modal is the same as it was before the intermediate robbing ever occurred.  This can subsequently lead to negative resources.

**Comment by xandroxygen** [comment]
The issue of discarding with < 7 resources is fixed, which should prevent this issue from ever occurring. Haven't yet been able to replicate the Robber starting before Discarding is finished.
