### ISSUE TITLE
[P4] [Team 5] [Phase 2] Buy Card Button Not Enabled After Trade

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#373]
I initially didn't have enough resources to buy a dev. card.  I proceeded to trade with another player, after which point I did have enough resources to buy a card.  However, the resource bar still did not let me purchase a card after the trade was finished.

**Comment by xandroxygen** [comment]
Unable to reproduce
Steps to reproduce:
1. log in as Sam. She needs 1 ore to be able to buy dev card.
2. Request trade with Brooke - 1 ore for 1 wood.
3. Log in as Brooke, accept trade:
   ![image](https://cloud.githubusercontent.com/assets/20050280/19775372/6f5e72fe-9c2d-11e6-8473-08bfdc34a9ac.png)
4. Log back in as Sam, trade has gone through. She has enough resources to buy a dev card and the button is enabled:
   ![image](https://cloud.githubusercontent.com/assets/20050280/19775420/8a39fd78-9c2d-11e6-8ae4-d57c098c482c.png)

**Comment by dannya951** [comment]
This may be another issue of having four clients running at once.  I'll test it later.

**Comment by xandroxygen** [comment]
No worries! I've noticed there is a ton of undefined behavior no matter what when you run 4 at once....

**Comment by dannya951** [comment]
I tried reproducing this one again.  I couldn't do it.  I think the issue is that I got it to happen when I was able to generate negative resources due to the discard/robber repetition issue.  As a result, I think it's fair to blame this behavior on the other issue that's already been reported.  So let's leave this one as invalid!

**Comment by xandroxygen** [comment]
Sounds good to me
