### ISSUE TITLE
[P3] [Team 5] [Phase 2] Hex Locations Not Congruent With Displayed Map

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#377]
I place the robber at a certain hex one the map, which isn't adjacent to anyone.  However, the game treats it like a completely different hex.  It allows me to rob a player on the other side of the map, and later disallows me from placing the robber on the hex to which that distant player is adjacent.

**Comment by spencerolsen** [comment]
I've tried to reproduce and am having a hard time doing so. For the steps that I describe below, I've done it a few times (in different locations that aren't adjacent to anyone), and I get the same results described below. Is this similar to what you did? 

This is what happened when I tried to reproduce. I was moving the robber to the hex above hex 5.

![2016-10-27 4](https://cloud.githubusercontent.com/assets/3418771/19780633/19faeba6-9c43-11e6-9f71-43cc242a8871.png)

After placing the robber, this is what shows

![2016-10-27 5](https://cloud.githubusercontent.com/assets/3418771/19780638/256b5796-9c43-11e6-9b2e-6b8a92376eee.png)

**Comment by dannya951** [comment]
In class right now.  Just let me know if this requires further explanation.  The robber starts at the upper left position in the first picture.  The last two or three images might be the most useful.
<img width="482" alt="1" src="https://cloud.githubusercontent.com/assets/21351700/19819129/7c8f82f4-9d10-11e6-81b9-bc77969fd024.png">
<img width="960" alt="2" src="https://cloud.githubusercontent.com/assets/21351700/19819132/7dd06750-9d10-11e6-98ef-5b3c9f2d80fe.png">
<img width="957" alt="3" src="https://cloud.githubusercontent.com/assets/21351700/19819135/7eded104-9d10-11e6-9fd2-c3850a87831a.png">
<img width="960" alt="4" src="https://cloud.githubusercontent.com/assets/21351700/19819136/7fcff3a4-9d10-11e6-934c-7f16c072a67c.png">
<img width="960" alt="5" src="https://cloud.githubusercontent.com/assets/21351700/19819137/80c27390-9d10-11e6-977a-b15a3c202093.png">
<img width="960" alt="6" src="https://cloud.githubusercontent.com/assets/21351700/19819138/81ac5e10-9d10-11e6-9298-593f784fe1a4.png">
<img width="960" alt="7" src="https://cloud.githubusercontent.com/assets/21351700/19819140/82eaa84a-9d10-11e6-80ff-6b70c3d653a7.png">
<img width="960" alt="8" src="https://cloud.githubusercontent.com/assets/21351700/19819141/83b91752-9d10-11e6-952e-c51b30e745fa.png">
<img width="960" alt="9" src="https://cloud.githubusercontent.com/assets/21351700/19819143/848bf906-9d10-11e6-8997-548205af3ed8.png">
<img width="960" alt="10" src="https://cloud.githubusercontent.com/assets/21351700/19819144/85439cc8-9d10-11e6-91a2-c3c60bf8f78e.png">

**Comment by dannya951** [comment]
You'll notice that when I hover over the hex two down from the one with the puce player (danny3), the map controller returns the information corresponding to the hex with the puce player.

**Comment by dannya951** [comment]
By the way, it looks like this creates a null pointer exception which crashes the client.  
<img width="960" alt="11" src="https://cloud.githubusercontent.com/assets/21351700/19819323/51bce82c-9d11-11e6-9040-fa9536fd3ae1.png">
<img width="960" alt="12" src="https://cloud.githubusercontent.com/assets/21351700/19819337/65b37e2c-9d11-11e6-8f22-157b9908a99b.png">
