### ISSUE TITLE
[P2] [Team 5] [Phase 2] Log in with previously registered user and can't rejoin game that user is already in

### ISSUE THREAD

**Issue by Rocker398** [cs340tabyu/cs340Winter2017#378]
It seemed to work normally until I played through a partial game, quit and restarted client. Once I logged back into that user, I couldn't rejoin the same game because it was "Full."

**Comment by xandroxygen** [comment]
Unable to reproduce.
1. Created new user Xander.
2. Created new game.
3. Played partial game (past setup).
4. Quit and relaunched client.
5. Logged back in as Xander.
6. Rejoined game. 
   ![image](https://cloud.githubusercontent.com/assets/20050280/19775584/26c95b16-9c2e-11e6-8f80-8d30f49826a3.png)

**Comment by xandroxygen** [comment]
Tested a few times, still unable to replicate
