### ISSUE TITLE
Turn Tracker doesn't show black border around current turn

### ISSUE THREAD

**Issue by joeddav** [cs340tabyu/cs340Winter2017#380]
When Sam clicks "end turn", the black border on turn tracker stays on Sam. Possibly related to #376 and #375

**Comment by daviscodesbugs** [comment]
@joeddav We can verify this bug, though propose it be a **P5**. The email sent out to the TAs give this explicit example "P5 (-0.5) - Stylistic errors (i.e. wrong color in the chat log) that has no effect on                                                    gameplay."

**Comment by abatschi** [comment]
fixed
