### ISSUE TITLE
Turn tracker doesn't show up sometimes

### ISSUE THREAD

**Issue by joeddav** [cs340tabyu/cs340Winter2017#388]
Seems to happen when the player logs and hasn't rolled yet, which is not very good when re-joining a game when it's someone else's turn and you can't see whose turn it is.

**Comment by daviscodesbugs** [comment]
@joeddav We can verify this. The case is that the turn tracker doesn't show up until after the setup phase, and it becomes the given player's turn. That's where we're calling the UI initialization logic. As this is purely a visual bug, we're proposing it's a P5.
