### ISSUE TITLE
Domestic trade doesn't show players to trade with

### ISSUE THREAD

**Issue by joeddav** [cs340tabyu/cs340Winter2017#391]

**Comment by daviscodesbugs** [comment]
@joeddav Playing the code that is up on the Google Doc, we are able to see the players who we can trade with. If you can give us more specific instructions on how to replicate this bug, we'll remove the invalid tag.
![domestic_trade](https://cloud.githubusercontent.com/assets/22112533/19818639/e0a20198-9d0d-11e6-8ae4-81cc85846abd.png)
