### ISSUE TITLE
Missing image in domestic trade receiving

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#41]
Domestic trading doesn't show the image for the resource to be received.
## Steps taken

I opened two clients. I created a trade on the first one. I then wen to the second client and was about to receive the trade when I noticed the image was missing. So, I have no idea what I'm receiving.

![missing_image](https://cloud.githubusercontent.com/assets/5455419/19735156/94121db0-9b67-11e6-92dc-20062da17ea8.png)

Makes it a little hard to know whether I want to accept the trade or not haha.

**Comment by wiseman5** [comment]
This doesn't happen for us, plus when you add a resource you add the resource and the amount at the same time in one function so I don't think this is our fault.

**Comment by dansteren** [comment]
Well, it's definitely not working. And "this doesn't happen for us" doesn't seem like a good excuse. Now, I don't know if this is a bug in the framework code or if you just didn't call the method correctly. (I don't think our's actually work's right). But I have seen it work elsewhere so I do think it's still your fault.

That being said, I guess I'm not really testing your team... So, I'll hand this off to team 10.

**Comment by wiseman5** [comment]
Does it do it to you every time or randomly or just the one time?  You are right about it being a problem if you can't see the image.  I didn't mean to say you were mistaken in reporting it.

**Comment by dansteren** [comment]
Got it. It just kinda seemed like you thought it was a mis-report since you slapped the "Invalid" label on there. It's all good though.

So, just tried again: it's every time. I just sign into the first game as two of the players. Then I initiate a trade with another player. When the dialog pops up for the other player that's where it doesn't display.

![missingagain](https://cloud.githubusercontent.com/assets/5455419/19746012/a828fd08-9b91-11e6-9e5f-b0f3b4af5b82.png)

I don't know why you aren't seeing this. Maybe you're running your code directly instead of `java -jar catan-client.java`. We were seeing discrepancies with ours when we did that. Beyond that I'm really not sure. I'm on Ubuntu 16.04 with java version 1.8.0_72. Also, I'm not running the jar from the same directory as my source code (also caused differences for us). Beyond that I'm not really sure what to say. It's pretty consistent on my system. Maybe get some other guys from Team 10 to give it a shot.

**Comment by wiseman5** [comment]
No,  I was running it from the jar.  I found some code that I think was the culprit, but I can't test to make sure because it doesn't happen to me.
