### ISSUE TITLE
GameListView: Newly created game doesn't include the user who created it

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#414]
According to the Functional Specs: "Pressing the “create” button should create a game, which should then show up in the game hub as a new game with one player."
When I create a game on the GameListView, it shows up in the list, but my name is not added to the new game.

**Comment by dansteren** [comment]
That was an oversight on my part. I'll work on implementing this

**Comment by dansteren** [comment]
Actually, my real thoughts on this is that the spec isn't the best solution. I think creating a new game should either just create the game (and not add you to it), or it should add you to the game and take you to the select color view

**Comment by dansteren** [comment]
I just talked to the TAs and they said that this was an acceptable behavior. So, I'm not going to change this.
