### ISSUE TITLE
Domestic Trade doesn't show type of resource in Accept Trade Offer for what the accepting player recieves

### ISSUE THREAD

**Issue by derbraun** [cs340tabyu/cs340Winter2017#416]

**Comment by xandroxygen** [comment]
Could you provide specific reproduction steps to get this? I have tried and have been unable to reproduce this, even by resizing the screen. Thanks!

**Comment by derbraun** [comment]
Did you run it from multiple clients? That is when a lot of bugs came out. I have one client on each of my 4 workspaces and then moved around.

**Comment by xandroxygen** [comment]
Ooh workspaces, I'd never thought of those for multiple clients. I've
always used split screen.

**Comment by derbraun** [comment]
![resource not displaying in trade](https://cloud.githubusercontent.com/assets/21980276/19789566/e5197f80-9c6d-11e6-82c1-9904a37c5349.png)

2 of what?
