### ISSUE TITLE
Player can't add a road or settlement near the edge of the map even though is valid location

### ISSUE THREAD

**Issue by derbraun** [cs340tabyu/cs340Winter2017#419]
![can t place settlement](https://cloud.githubusercontent.com/assets/21980276/19754504/5479f1fa-9bcb-11e6-9cfb-215212d9d51f.png)

**Comment by jerekeith2** [comment]
In your screen shot, you are trying to post a settlement in an invalid location.  From the spec: 
"Settlements must be placed two or more roads segments away from each other".

Please provide a different example.

**Comment by derbraun** [comment]
Sorry, I misunderstood the specifications with the map

**Comment by jerekeith2** [comment]
All good! Closing.
