### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#423]
Sending a message didn't work, restarting the client didn't work, I had to restart the server and it worked fine...

**Comment by cojoco** [comment]
I'm not sure I quite understand this issue. Is it that chat wasn't working? Or was nothing in the client working? If it was just chat, why is this a P2 bug?

**Comment by cojoco** [comment]
I'm going to tentatively label this "Unable to Replicate" until we get more information on what was happening.
