### ISSUE TITLE
Games list isn't updated on other clients

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#425]
Steps taken:
I started up 4 clients pointing to a server on localhost:8081 and logged into 4 different account (one on each client). I created a new game on one client and it propagated across the rest of the clients. Then I created a second game on another client and it didn't sync.

I don't think that your view is getting refreshed until someone creates a game. I made a third game on another client and then the second game from the second client came through.

Yeah, so, it looks like your server poller doesn't update this list of games. That means that if 4 people all log in and then one person creates a game, the other clients can't see or join it. Game over.

**Comment by smithskyler** [comment]
I think that this is P3. The game isn't totally stopped, it's just a little weird. You could still get into that game if you wanted just by creating a new game.

**Comment by smithskyler** [comment]
This is actually the same problem as #104.

**Comment by ringmaster217** [comment]
This is not a requirement mentioned in the spec for this project. Also, while it may be somewhat aggravating, it doesn't break any gameplay.

**Comment by dansteren** [comment]
From the functional spec:

> Pressing the “create” button should create a game, which should then show up in the game hub as a
> new game with one player.

@ringmaster217 I suppose it's not in the spec because it just doesn't say anything about what other client's are supposed to do. But I think it's implied that all player's should get updated when any user creates a game. It's not a hard fix, and I think it should be implemented.

@smithskyler I'll let you handle the level. I think you could be any level P2-P5 depending on how you argue it.
