### ISSUE TITLE
Unable to place settlement after logging back in 

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#426]
I quit the game after Setup phase 1 was finished, restart the game and logged back in. The Place Settlement overlay came back up to start Setup phase 2, which is correct, but now no matter where I roll over on the map it shows a red circle sign on every location, even when no other buildings are close by.

**Comment by Redge-Ballard** [comment]
I haven't been able to replicate this error... Do you happen to have any more details about what you did to make this happen? Was in a 1 player 3 ai game? Multiple human players?
