### ISSUE TITLE
Setup phase 1: Game doesn't auto-advance

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#427]
I'm testing with 1 actual player and 3 AI players, and as soon as I place my first road/settlement combo, the Place Road overlay goes away and I'm stuck waiting for the AIs to finish their "turns" but the game just stays there indefinitely.

**Comment by Redge-Ballard** [comment]
I think this might be related to the fact that we don't automatically end the turn after the setup phase. The finish turn button becomes enabled, so technically you can end your turn, but according to the specs it should just go forward automatically. I'll look into it.

**Comment by Redge-Ballard** [comment]
Just as i suspected. I'll make this automatically end the turn after you place the settlement.
