### ISSUE TITLE
Incorrect colors for placing road on 3rd/4th client

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#428]
I started playing through a game. In the very first round, the first two people each play a road and a settlement. I then switched over to the third and forth players and the second player's color was showing up for the road piece.

![colorsoff](https://cloud.githubusercontent.com/assets/5455419/19754834/46ce0d72-9bce-11e6-9cb0-fdaaed809f26.png)

![4thperson](https://cloud.githubusercontent.com/assets/5455419/19754911/d303e2a8-9bce-11e6-92c7-8ec8e9284435.png)

**Comment by smithskyler** [comment]
This is the same as #442. What you're seeing is the ability to play the piece of another player. That's why, in the above screenshots, you can't see where yellow's pieces have actually been placed.
