### ISSUE TITLE
Finish turn

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#430]
clicked on finished turn but was still able to do domestic trade and maritime trade. The Rolling modal was showing on the next player

**Comment by mike0256** [comment]
I haven't been able to reproduce this error. Could you attach an image or expound a little further on the error? How many players were humans? Were you actually able to make a trade? Did the button at the bottom say "Waiting for other players"? Any more information you could give us would be greatly appreciated. Thanks.
