### ISSUE TITLE
Other player's pieces not painting to the screen

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#432]
I placed a road and settlement for players one and two in the first round. I then went to place a road and settlement for player 3 and he can't place his where the second player's is, but it doesn't actually show up on the overlay, just the "no" symbol.

Here we have player 2 (Adrian - yellow).
![player2](https://cloud.githubusercontent.com/assets/5455419/19754972/598a154a-9bcf-11e6-9804-26726f864ede.png)

And here's player 3 (Redge - green).
![player3](https://cloud.githubusercontent.com/assets/5455419/19754984/7e3a7a10-9bcf-11e6-9559-9dbe41586af0.png)

I'm marking this as P3 because player 3 would have no reason to believe he couldn't place a road there and would think the game was broken. From his point of view, he should be able to place a road there.

**Comment by smithskyler** [comment]
This is the same as #442. It's trying to let you place a piece for yellow.
