### ISSUE TITLE
Discard

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#433]
Had to discard 1 card, asked me to discard 4
![capture d ecran 2016-10-26 a 23 00 27](https://cloud.githubusercontent.com/assets/14816161/19755104/5cb5981a-9bd0-11e6-973f-1c82831d1e5d.png)

**Comment by mike0256** [comment]
I'm pretty sure this is correct functionality. As far as I understand the rules, if you have more than seven cards then you have to discard half of the cards that you have, rounding down. So, since you had eight cards you'd have to discard four.
