### ISSUE TITLE
Turn order is not enforced (at least during initial setup)

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#435]
I created a new game and placed settlements and roads for players 1 and 2, in order. When it came time for player 3 to take his turn, player 4's UI had already updated and was allowing him to place roads out of turn. So, at this point, the game was acting as if it was both player 3's and player 4's turn.

I'm marking this as a P2 because if player 4 goes before player 3 then the whole system stops. I placed a road for player 4 before placing player 3's pieces. When I did the overlay closed and went to waiting for player 3. I then placed player 3's road and the overlay closed and now it just sits there. Now everyone's screens just say "waiting for players..."

**Comment by dansteren** [comment]
**Update:** It's not just player's 3 and 4. I started a new game, placed player 1's road and settlement and then looked at all the other clients. They all act as if it's their turn. I'm sure if anyone goes out of turn then the game breaks.

**Comment by smithskyler** [comment]
It seems that this is only reproducible when all 4 clients are being run on the same computer using a localhost server. It's also not exactly what is being described. The other players can't place their own pieces when it's someone else's turn. They can place the piece of the person who's turn it is.

**Comment by smithskyler** [comment]
I think I've fixed this. This bug doesn't happen 100% of the time, which makes it difficult to test, but I can't get it to happen anymore.
