### ISSUE TITLE
PlayerWaitingController doesn't show the Current players in the game.

### ISSUE THREAD

**Issue by skunkworker** [cs340tabyu/cs340Winter2017#436]
The PlayerWaitingController view doesn't show the current players in the game above the "Player Waiting View"

![screenshot 2016-10-26 23 09 38](https://cloud.githubusercontent.com/assets/2637951/19755207/5a90ded6-9bd1-11e6-8d23-1ba5ddc711c1.PNG)

**Comment by isaiMercado** [comment]
fixed
