### ISSUE TITLE
Incorrect password causes client hang.

### ISSUE THREAD

**Issue by skunkworker** [cs340tabyu/cs340Winter2017#439]
When inputting the incorrect password for a user, regardless if the user exists, the client will hang and become unresponsive. Only force quitting the client will allow the client to be exited.
![screenshot 2016-10-26 23 14 29](https://cloud.githubusercontent.com/assets/2637951/19755292/f7e9fa5a-9bd1-11e6-9970-c857419bfa05.PNG)

**Comment by isaiMercado** [comment]
fixed
