### ISSUE TITLE
Map drawn in the Chat Message area

### ISSUE THREAD

**Issue by mike0256** [cs340tabyu/cs340Winter2017#441]
I started my turn, sent a message, and got the map drawn in the Chat Message area.
![mapinmessages](https://cloud.githubusercontent.com/assets/21963969/19755378/b49ae7b8-9bd2-11e6-8376-8276f608e905.PNG)

**Comment by Chroniclerz** [comment]
Bug inherent to the UI interface, unfortunately. All clients utilizing the UI will have this problem.
