### ISSUE TITLE
Registration failures display bad messages

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#45]
I tried registering a new user with the following:
- username: "Daniel"
- password: "daniel"

As far as I can tell, this should be a valid user registration, however, it fails:

![registrationfails](https://cloud.githubusercontent.com/assets/5455419/19735646/b07b6dd8-9b69-11e6-82e8-0e4794cd0772.png)

**Comment by dansteren** [comment]
Console output:
![terminal](https://cloud.githubusercontent.com/assets/5455419/19735852/785dc08a-9b6a-11e6-9981-37724d6c1f60.png)
 Also, I'm running this with my team's server using `ant server`. I don't know if that makes a difference but doing `java -jar catan-server.jar` doesn't work.

![catan-server-missing](https://cloud.githubusercontent.com/assets/5455419/19735949/de92d782-9b6a-11e6-8eac-f2a5fc404b59.png)

**Comment by dansteren** [comment]
Also, this is more just a UI thing, but I couldn't even see all the fields when registering

![can t see fields](https://cloud.githubusercontent.com/assets/5455419/19735980/05e7a9ca-9b6b-11e6-907a-d9689dbf20de.png)

**Comment by kalebo** [comment]
@xaves you must be grading the wrong group. Group 10 will be grading group 11 as per the spreadsheet from the TAs.

**Comment by athompson909** [comment]
Hey this is Adam from team 11, as far as not being to see all the fields in the register area all you need to do is make the window taller... I have the same error on my macbook air

**Comment by athompson909** [comment]
and maybe the reason you weren't able to register because the password repeat field wasn't filled in because the UI didn't let you get to the second one, a server error would result in that case

**Comment by SierraD012** [comment]
@xaves - When you tried registering as Daniel, was that the first time that name had been used to register? We know that the JSON request to the server is correct, and so as far as we know the only situation that the server would return a 400 response would be if Daniel already exists as a user.

**Comment by dansteren** [comment]
@kalebo my bad. The spreadsheet is laid out terribly. I read it as each line is information about a team, one of the columns being who will grade that team. 

| Team | will grade | Email(s) | Code |
| --- | --- | --- | --- |
| 11 | 12 | sd.birdlover@gmail.com | https://drive.google.com/open?id=0B-xjZzk0W35HU2pvTE9DaVZnOE0 |

**Comment by dansteren** [comment]
@SierraD012 Ok, so this is just a botch of a thread. Turns out that I had somehow made the client already and that was why the request was failing. Sorry about that...

I guess the saving grace is that your error message should be updated. Telling the user that the request failed isn't helpful. You should tell them that the user already exists. Otherwise they are are just going to assume that it's your fault an that your code is busted. That's what happened to me. I'll change the level but I still think this is a bug.

**Comment by dansteren** [comment]
@athompson909 yeah, I would if my screen got any bigger. That window was already at it's max. I understand it's not really your fault (more java swing's) but just the same...

**Comment by SierraD012** [comment]
@xaves Got it. We just changed that error message as a part of our debugging process about an hour ago, so no worries. Thanks!
