### ISSUE TITLE
Missing image in domestic trade receiving

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#453]
I just created a domestic trade from player 1 to player 2. I offered to trade 1 sheep for 1 wood. When I went to player 2's screen the sheep icon is missing.

![missingsheep](https://cloud.githubusercontent.com/assets/5455419/19755874/fd3e6032-9bd5-11e6-9413-d49175f14944.png)

I'm marking this as P3 because the player would have no idea whether they would like to accept the trade or not, without knowing what they are receiving.

**Comment by smithskyler** [comment]
I think that justification for P3 is that the actual rules of the game are messed up. If not, then anything (even color mistakes in the message log) are P3 because you're not sure who sent them. This contradicts the TAs statement. This should be P4.

**Comment by ghost** [comment]
We've tested this several times, and are unable to reproduce the bug. We've tried different people trying different trades, and each time the pictures are showing up fine. I think it might be a one-time UI bug.
![sheepforwood](https://cloud.githubusercontent.com/assets/22104776/19818332/971bcf96-9d0c-11e6-8dbf-973df87a054a.PNG)
