### ISSUE TITLE
Game state button color

### ISSUE THREAD

**Issue by lastmjs** [cs340tabyu/cs340Winter2017#454]
I've actually been wondering what the answer to this is myself. The functional spec says the following about the game state button:

```
When enabled, the button should display with the player’s color.
```

That does not happen with the client though. I'm not sure it is even possible, but that's what the spec says.

**Comment by ringmaster217** [comment]
This is a bug in the UI code, not something we wrote.

**Comment by bmarker6** [comment]
Fixed
