### ISSUE TITLE
Development cards not available

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#458]
On my turn I purchased a development card. After purchasing it however, I was unable to click on the development card button to see which card I had received. After clicking on the "Finish my turn" button it became enabled again, but by that point I couldn't click on it because it wasn't my turn.

**Comment by smithskyler** [comment]
I see now that we implemented this a little incorrectly. We made so that only your playable cards are ever visible, and you can only see the cards you have if you can play one. Because this is the case, this bug does not affect gameplay. It is only inconvenient.

**Comment by smithskyler** [comment]
I'm changed this to match the spec.
