### ISSUE TITLE
Players display boxes don't show the current player, boxes of color appearing in the longest road and largest army JPanels. Names being overwritten every time and becoming more and more blurry.

### ISSUE THREAD

**Issue by jcwheatley** [cs340tabyu/cs340Winter2017#459]
![screen shot 2016-10-26 at 11 46 34 pm](https://cloud.githubusercontent.com/assets/8496623/19755995/e563dd88-9bd6-11e6-9820-04ed139833a1.png)

**Comment by michaelpratt28** [comment]
This is a problem with the GUI, not with our code.
