### ISSUE TITLE
Placing a settlement ends turn

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#461]
I purchased a settlement and placed it on the map. I was hoping to still do maritime trade (I just built on a port ;)) but it had already ended my turn.

This happened for me with two separate players. So, it has been reproduced.

**Comment by ringmaster217** [comment]
I can't replicate this bug.

**Comment by smithskyler** [comment]
Neither can I. I played through a whole game, and built 2 settlements on ports, and this never happened.

**Comment by MCTWalker** [comment]
I can't replicate this bug.
