### ISSUE TITLE
[P3][Team5][Phase2] Game breaks when any player reaches 10 points

### ISSUE THREAD

**Issue by csivek** [cs340tabyu/cs340Winter2017#463]
When 10 points is reached, game breaks and does not show anything. Player may continue pulling up views, but the game itself cannot be changed.

**Comment by spencerolsen** [comment]
Do you mind leaving the steps to reproduce? (Playing with AI players? If not, were all 4 players from your machine or were you playing with someone else?) I included screenshots below of what normally happens for me, so I just want to figure out under what conditions that happened...

This is what first shows up when I reach 10 points:
![2016-10-27](https://cloud.githubusercontent.com/assets/3418771/19780089/1bfe30e0-9c41-11e6-97d0-4bbf0e02aa3a.png)

After clicking OK, this is the next screen that pops up:
![2016-10-27 1](https://cloud.githubusercontent.com/assets/3418771/19780168/4a23d826-9c41-11e6-8fe1-b633fa2f5d52.png)

From there I was able to join another game and pick up where it left off.

**Comment by csivek** [comment]
csivek@yellowstone:~$ cd Downloads
csivek@yellowstone:~/Downloads$ cd 5
csivek@yellowstone:~/Downloads/5$ java -jar catan-client.jar
Exception in thread "Timer-1" java.lang.IndexOutOfBoundsException: Index: 12, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at client.points.PointsController.update(PointsController.java:61)
        at java.util.Observable.notifyObservers(Observable.java:159)
        at client.model.Model.updateModel(Model.java:175)
        at client.server.ServerPoller.pollServer(ServerPoller.java:100)
        at client.server.ServerPoller$1.run(ServerPoller.java:66)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

It happens every time I try to win the game. It could be that your submitted file was an older one that someone from your team fixed on your end

**Comment by csivek** [comment]
Oh. This problem happens both with and without other client players. And the above stack trace is the exception thrown when the game freezes

**Comment by xandroxygen** [comment]
Seems that despite the server spec explicitly saying the winner is passed as an index, we are receiving the winner as a playerID, which is why the OOB exception occurs. 

Also, seeing as the game is over when this occurs, I would downgrade this to a P4, consistent with what other groups have rated bugs like this. Gameplay is not affected at all.

**Comment by csivek** [comment]
Most teams put P3 (error that affects gameplay) for cannot end game. But I put P2 because it's an exception thrown that stops everything from working as described in the email. I will meet you halfway and label it P3 (because it still does affect gameplay)

**Comment by xandroxygen** [comment]
Done and done
