### ISSUE TITLE
Unable to place a city

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#465]
I tried building a city on top of my settlement and was unable. I actually couldn't place it anywhere on the whole board.
![nocity](https://cloud.githubusercontent.com/assets/5455419/19756266/8ee4cb3c-9bd8-11e6-9dac-b801349c3bec.png)

**Comment by ringmaster217** [comment]
I can't replicate this bug.

**Comment by jerekeith2** [comment]
I can't either. It looks like faulty game data created from a different client was loaded into our client.  It doesn't make any sense to me why there would be a road placed on the top left hex #8 without any kind of settlement touching it.  I don't think our client would let that happen...

**Comment by smithskyler** [comment]
I can't replicate this bug either.

**Comment by MCTWalker** [comment]
I think playing devcards could change the mapstate and cause this bug to happen, so I'm going to look at it.

**Comment by MCTWalker** [comment]
I couldn't ever reproduce this error.
