### ISSUE TITLE
During setup the order of settlement and road placement is reversed.

### ISSUE THREAD

**Issue by cojoco** [cs340tabyu/cs340Winter2017#47]
During setup, the player is asked to place a settlement first, followed by a road. In the example gameplay video, it shows the road being placed first, followed by a settlement. Everything gets placed in the end, though.

**Comment by chaserobertson** [comment]
In the Settlers of Catan rulebook, it does not state whether road or settlement should be placed first. It doesn't actually matter, as each player places both during their turn. We chose to do it this way deliberately, and Dr. Woodfield has validated our decision.
