### ISSUE TITLE
[P2][Team 5][Phase 2] Attempted to build road when no roads left for player. Modal for placing road did not have cancel function

### ISSUE THREAD

**Issue by csivek** [cs340tabyu/cs340Winter2017#470]
Soft Locked because I couldn't cancel building a road and no valid locations to build a road existed

**Comment by xandroxygen** [comment]
Unable to reproduce, see screenshot. Are you sure you were using team 5's code and not a different team's? That happened to us for a little bit yesterday.
![image](https://cloud.githubusercontent.com/assets/20050280/19774475/6da264fa-9c2a-11e6-9a66-d16fe17ae627.png)

**Comment by csivek** [comment]
Sorry, it was the modal for placing a road after a player ran out of
pieces. Not maritime trading. (Screenshot seems to be for something else?)

**Comment by xandroxygen** [comment]
Sorry, thought I updated the screenshot (it was a bad copy paste haha). edited comment should have correct screenshot of placing a road:
![image](https://cloud.githubusercontent.com/assets/20050280/19776889/145235ca-9c33-11e6-9419-2047e0541a9a.png)

**Comment by csivek** [comment]
Ok. As a note. I produced it while running two clients in one game

**Comment by xandroxygen** [comment]
yeah that seems to be a theme...that produces undefined behavior. I would try only using one client.
