### ISSUE TITLE
Discard all cards - [Group 14][Phase 2][P5]

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#471]
If you have more than 7 cards and someone rolls a 7 the discard controller pops up prompting you to discard cards.  You are required to discard half of your cards, rounded down - if you have 9 you discard 4, however, you are allowed to discard all your cards.
![discard](https://cloud.githubusercontent.com/assets/161021/19759305/a5f64524-9be9-11e6-9b34-944a6abc7a7e.png)

**Comment by abatschi** [comment]
fixed where you cant discard more than whats called for
