### ISSUE TITLE
You can initiate maritime trades when it is not your turn - [Group 14][Phase 2][P3]

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#474]
You should not be able to perform Maritime Trades with the bank when it is not your turn.

![trade](https://cloud.githubusercontent.com/assets/161021/19759713/7f82eefe-9beb-11e6-8de9-6fddd2774401.png)

**Comment by Napper15** [comment]
Duplicate to https://github.com/cs340tabyu/cs340fall2016/issues/476
