### ISSUE TITLE
Perform Action during another users turn

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#476]
While the game is paused after another player rolls a 7 you can perform actions for that user such as building settlements and roads.

In this image I am the test user.  It is Squalls turn, but it allows me to place a settlement for him.
Red X to show before
![other_user1](https://cloud.githubusercontent.com/assets/161021/19760334/86798698-9bee-11e6-9776-2a689d65f847.png)

Settlement on the general port to the left of Red X
![other_user](https://cloud.githubusercontent.com/assets/161021/19760387/c98d3b5a-9bee-11e6-896c-0495e1ca2bc7.png)

**Comment by dolson25** [comment]
Fixed!  Stupid bug.  Just missing an else blocK   :|
