### ISSUE TITLE
Game List does not update

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#479]
The list of games does not update with players joining or creating new games.  The client in the upper left corner was client provided by the TA's which shows the bottom left game in waiting.  The upper right client does not display the pending games.  The terminal output does not indicate the poller issuing a command to get new games.

![update_list](https://cloud.githubusercontent.com/assets/161021/19761207/2c34f2e0-9bf2-11e6-97ac-970a1c42beb3.png)

**Comment by abatschi** [comment]
duplicate of 480

**Comment by mhnsn** [comment]
Fixed as of [pull request #24](https://travis-ci.com/mhnsn/CS_340/builds/34050169); needs review before merging.
