### ISSUE TITLE
Creating game locks up screen, requiring restart

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#504]
I registered user string, then clicked create game. I then input name test1. This brought me to the screen in the picture below (with no input options). I also ended up with 2 copies of game test1
![bug1](https://cloud.githubusercontent.com/assets/22157895/20399987/38aaad70-acb0-11e6-8aee-d80c529142bf.png)

**Comment by Chroniclerz** [comment]
Sorry, wrong picture. It doesn't allow preview here
![bug1](https://cloud.githubusercontent.com/assets/22157895/20400058/75da5c18-acb0-11e6-952c-28b4df0b349e.png)

**Comment by Chroniclerz** [comment]
Based on the research of other group members, we believe this is a modal issue. Probably caused by updating the information inside the join game modal.
In order to update information inside a modal it is often required to "blink" it. close the modal, then open it again.

**Comment by victorlazaro** [comment]
It's easily fixed by resizing the screen.

**Comment by Chroniclerz** [comment]
It also created 2 copies of game test1, which is not fixed by resizing screen

**Comment by Chroniclerz** [comment]
I managed to reproduce the double game creation bug. It doesn't happen every time. I can't really figure out the impetus to it. Might have to do with rapid clicking or something. Also, simply "resizing" the window leads to a significant graphical glitch as the modal can't properly display itself
![bug17](https://cloud.githubusercontent.com/assets/22157895/20449868/4e03b6e0-ada9-11e6-95ef-84a0f871ad37.png)
