### ISSUE TITLE
Player may perform other actions while discarding is happening.

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#515]
As displayed, a player has rolled a 7 and was not brought to robbing or to a wait screen. Instead Player 1 was brought to discarding (with his monstrous 44 resources cards). However player 2 (he who rolled a 7) can do anything he would normally do on his turn
Player 1 actually discarding causes the game to freeze up as everyone is brought to a "Waiting for other players to discard" screen. Thus blocking gameplay when a discard happens.
Game had to be "discarded" thus, bug is blocking gameplay

**Comment by TravisAGengler** [comment]
If you could add a picture of what happened, that would be helpful. Thanks!

**Comment by Chroniclerz** [comment]
Its hard to get details, but this is a screen showing all 4 simultaneously  in player waiting
![bug16](https://cloud.githubusercontent.com/assets/22157895/20449736/6fe47976-ada8-11e6-9f2b-af8f7e1f4c00.png)
this is the player whose turn it is
![bug16-1](https://cloud.githubusercontent.com/assets/22157895/20449756/8db1dd72-ada8-11e6-92b5-9d28d2dab9c3.png)
This is another player who was discarding
![bug16-2](https://cloud.githubusercontent.com/assets/22157895/20449766/a62f541a-ada8-11e6-951b-479cbb312082.png)
And the following 2 are the players who didn't discard
![bug16-3](https://cloud.githubusercontent.com/assets/22157895/20449787/c36d7714-ada8-11e6-845b-5ef8eb5fcc07.png)
![bug16-4](https://cloud.githubusercontent.com/assets/22157895/20449799/d876a126-ada8-11e6-9df8-d6abd1e87d4f.png)
Hopefully thats enough to help. Let me know if there is anything else I can provide you with
Sadly I can't scroll the log for an image of that

**Comment by TravisAGengler** [comment]
Thanks!
