### ISSUE TITLE
Longest road counts number of roads, not largest sequence

### ISSUE THREAD

**Issue by janderson11** [cs340tabyu/cs340Winter2017#520]
![longest road p4](https://cloud.githubusercontent.com/assets/16613396/20408231/cbce2868-acd1-11e6-8746-79b1fdae5a52.PNG)

**Comment by mclements37** [comment]
![longestroadsnippet](https://cloud.githubusercontent.com/assets/21322207/20416417/1a3a39ae-acfc-11e6-99ad-5ca1eddd7f1e.JPG)
Marking as invalid according to the specs.
