### ISSUE TITLE
[P5][Team 6][Phase 3] Maritime Trade doesn't visually block player from trading even when he/she cannot trade

### ISSUE THREAD

**Issue by csivek** [cs340tabyu/cs340Winter2017#524]
Fortunately it doesn't seem to break the model, stop gameplay, or change anything that it cannot

**Comment by intcreator** [comment]
You should add labels to this issue instead of including that information in the title.

**Comment by derbraun** [comment]
For some reason, csivek is unable to add labels to the issue. Assigning labels
