### ISSUE TITLE
Game with 3 AI players does not start 

### ISSUE THREAD

**Issue by kr4of6** [cs340tabyu/cs340Winter2017#526]
I can only add one AI player and then the game enters a player waiting state and I cannot do anything 

<img width="1342" alt="screen shot 2016-11-17 at 3 51 17 pm" src="https://cloud.githubusercontent.com/assets/15623981/20411264/f06e2d6a-acdd-11e6-9ffb-5b64b1e97e19.png">

**Comment by intcreator** [comment]
You should add labels to this issue so the team it belongs to knows it applies to them.
