### ISSUE TITLE
Starts game with less then 4 players 

### ISSUE THREAD

**Issue by kr4of6** [cs340tabyu/cs340Winter2017#528]
"adds AI" but does not actually add the AI

**Comment by intcreator** [comment]
Can you include more details?  Like a screenshot perhaps?  We're not sure what this means.

**Comment by dansteren** [comment]
@kr4of6

**Comment by intcreator** [comment]
This may be some simple logic in the TurnTracker that doesn't show AI players as added even though they're added to the game state.  If that's the case, then this has the wrong severity classification (it should be a P5 because it's an error displaying something on the GUI).

**Comment by kr4of6** [comment]
Sorry, I just saw your comments here are some screen shots: 
<img width="772" alt="screen shot 2016-11-21 at 3 19 07 pm" src="https://cloud.githubusercontent.com/assets/15623981/20503031/f353b928-affd-11e6-8912-dc964b78ca12.png">

I am in the game with 2 AI I click add AI which then closes the model. I am then stuck on this screen 

<img width="1279" alt="screen shot 2016-11-21 at 3 19 15 pm" src="https://cloud.githubusercontent.com/assets/15623981/20503033/f634dcee-affd-11e6-9771-fa604de54f13.png">


I am never prompted to play a road or settlement and thus game play is blocked Thus, I believe it is still a P2 because the game play is blocked I am stuck at this point waiting for other players and can never move past this point

**Comment by dansteren** [comment]
If that is indeed the case then **kr4of6** is right and it should still be P2. @Redge-Ballard Does the stuff you're working on fix this?

**Comment by dansteren** [comment]
Current Code:
```java
@ActionName("addGameAI")
public static ServerState addGameAI(ServerState state, int gameId, AIType aiType) {
	Atom<Integer> playerIndex = atom(-1);
    // update players in state
    return (ServerState) updateIn(state
		,	vec("clientModels", gameId, "players")
		,	(Fn1) (playersObject) -> {
	            List_Player players = (List_Player) playersObject;
				reset(playerIndex, count(players));
	            // add AI player
	            return conj(players, create(  Player.class
	                                        , hashMap(  "color"       , getRandomEnum(CatanColor.class, players)
	                                                  , "name"        , getRandomName(players)
	                                                  , "playerID"    , 0 // playerID doesn't really matter
	                                                  , "playerIndex" , get(playerIndex))));
    		}
		,	vec("aiPlayers", gameId)
		,	(Fn1) (s) -> eq(s, null) ? hashSet(get(playerIndex)) : conj(s, get(playerIndex))
		);
}
```
I think we just need to add some logic that says, if this is the last player to be added then progress to phase 1.

**Comment by dansteren** [comment]
Actually, I think this is a client side issue

**Comment by dansteren** [comment]
I take it back, our client behaves just fine with the TA server

**Comment by dansteren** [comment]
It was stupid premature optimization. Fixed thanks to @lastmjs!
