### ISSUE TITLE
Resources distributed incorrectly

### ISSUE THREAD

**Issue by smithskyler** [cs340tabyu/cs340Winter2017#531]
After the second setup phase, I checked that all the resources were assigned to the players properly (1 resource for each hex next to their 2nd settlement), and they were. Then, Player 1 (Slimey), automatically rolled a '10'. I checked again to make sure that the resources were assigned properly, but this time, they weren't. Players 1 and 4 (Slimey and Tester 3) should have each received 1 sheep. Instead, resources were given as follows:
Slimey: 1 sheep & 1 wheat
Tester 1: 1 wood & 1 wheat
Tester 2: 1 ore & 1 brick
Tester 3: 2 sheep

I noticed that this kept happening as the game went on. It looks like on every roll, each player is given 1 resource for the hex directly southeast of each settlement they have.
![screen shot 2016-11-17 at 4 38 07 pm](https://cloud.githubusercontent.com/assets/20779308/20412489/46c307b6-ace4-11e6-862b-b28ae6d6978c.png)
![screen shot 2016-11-17 at 4 38 41 pm](https://cloud.githubusercontent.com/assets/20779308/20412502/5bac838c-ace4-11e6-8452-82b4a7455377.png)
![screen shot 2016-11-17 at 4 38 48 pm](https://cloud.githubusercontent.com/assets/20779308/20412505/5bd7e428-ace4-11e6-8164-09f297b7648d.png)
![screen shot 2016-11-17 at 4 38 56 pm](https://cloud.githubusercontent.com/assets/20779308/20412504/5bd72eca-ace4-11e6-9dfa-957a9e8aa858.png)

**Comment by csydvs** [comment]
see #540, we really only had one issue with distributing resources, it was just a nasty one:)
