### ISSUE TITLE
Domestic Trade doesn't work

### ISSUE THREAD

**Issue by smithskyler** [cs340tabyu/cs340Winter2017#536]
I can't do a domestic trade. When I offer a trade to a player, that player has no opportunity to accept it. Then, in a few seconds, the trade is cancelled automatically and a message is logged saying that the player who offered the trade rejected it. No players in the game were AIs.
![screen shot 2016-11-17 at 4 51 30 pm](https://cloud.githubusercontent.com/assets/20779308/20412855/90658b58-ace6-11e6-8c90-32594bc86fb8.png)

**Comment by csydvs** [comment]
See #627
