### ISSUE TITLE
Rolling modal pops up continuously

### ISSUE THREAD

**Issue by smithskyler** [cs340tabyu/cs340Winter2017#540]
The rolling modal appeared and disappeared continuously at the beginning of a player's turn. At first, clicking 'roll' just made the modal reappear. Eventually, after letting it try to automatically roll several times, it finally rolled a '7'.

Once it started happening, it happened on every player's turn, and they only ever rolled 7s, over and over. 

This started happening after every player only rolled on their turn and did nothing else for a few rounds in a row, and then a 7 was rolled. Because of #538, everyone lost all their resources, so no one could be robbed. After the first time only 7s were ever rolled, so no one could ever get resources ever again. The game was essentially broken.

![screen shot 2016-11-17 at 5 20 46 pm](https://cloud.githubusercontent.com/assets/20779308/20413437/4fda1898-acea-11e6-92d2-6845634fa1b8.png)
![screen shot 2016-11-17 at 5 21 00 pm](https://cloud.githubusercontent.com/assets/20779308/20413438/4ff2ef30-acea-11e6-840e-07f610e3b269.png)

**Comment by csydvs** [comment]
See #658
