### ISSUE TITLE
Forced to finish turn on set up (round one or round two) 

### ISSUE THREAD

**Issue by kr4of6** [cs340tabyu/cs340Winter2017#541]
After I play my road and settlement I am forced to click finish turn to end my turn. This should be done automatically. 

<img width="1370" alt="screen shot 2016-11-17 at 5 51 02 pm" src="https://cloud.githubusercontent.com/assets/15623981/20414190/74c6d99e-acee-11e6-970d-76482c12c803.png">

**Comment by intcreator** [comment]
@lastmjs said he talked to a @cs340tabyu and found that this was not a valid issue.
