### ISSUE TITLE
Creating a new game removes all games from the game list and removes options

### ISSUE THREAD

**Issue by tsmith1644** [cs340tabyu/cs340Winter2017#543]
I created a new game with 4 clients open and when all of the join game views went blank. Resizing the window refreshes the view with correct data.
![screenshot 5](https://cloud.githubusercontent.com/assets/22157898/20414264/c801f6e8-acee-11e6-8002-d9ba45491c21.png)

**Comment by tsmith1644** [comment]
This happens anytime the game list has information updated. I added a player to one of the games and it happened again.
![screenshot 6](https://cloud.githubusercontent.com/assets/22157898/20414803/a8569a12-acf1-11e6-9215-afd0bdd0a115.png)

**Comment by TravisAGengler** [comment]
Resizing the window, or minimizing the window and then maximizing it will fix this. We arent exactly sure why this happens, but it has to do with the UI's responsiveness to changed data. We have discussed this with the TA's and they reassured us that it is not an issue.
