### ISSUE TITLE
Registering a new user doesn't work

### ISSUE THREAD

**Issue by csydvs** [cs340tabyu/cs340Winter2017#547]
If I try to register username "Sam" and password "sam," then it says 
![image](https://cloud.githubusercontent.com/assets/15003465/20415116/89339c14-acf3-11e6-8899-d3c170758c38.png)

"Sam" and "sam" don't let me login either, so I don't think this is because it's already a username

**Comment by garretthoffa** [comment]
Sam is an invalid password because it needs to be longer then 3
