### ISSUE TITLE
First and Second round player plays settlement first 

### ISSUE THREAD

**Issue by kr4of6** [cs340tabyu/cs340Winter2017#56]

**Comment by mclements37** [comment]
The official rule book from [https://students.cs.byu.edu/~cs340ta/fall2016/group_project/Catan_Rules.pdf](url) states: "The starting player **places a settlement** on an open intersection of his
choice. He **places a road adjacent to this settlement**. The other players then follow clockwise. Everyone places 1 settlement and 1 adjoining road." Hence, this is not incorrect behavior, but following the official almanac.
