### ISSUE TITLE
Not able to place roads in first-round modal

### ISSUE THREAD

**Issue by jasonmck** [cs340tabyu/cs340Winter2017#561]
When I open up four clients and all join a game, the first player who is supposed to start the game is presented with this window in which nothing can happen.

**Comment by jasonmck** [comment]
<img width="1437" alt="screen shot 2016-11-17 at 7 12 43 pm" src="https://cloud.githubusercontent.com/assets/16066003/20416137/35affc48-acfa-11e6-85a2-d716ed5c20f1.png">

**Comment by jasonmck** [comment]
P2

**Comment by intcreator** [comment]
Try resizing the window.  This is a P5 bug on our client.  The client window doesn't refresh unless you resize it or something.
