### ISSUE TITLE
Can have two clients in the same game as the same user

### ISSUE THREAD

**Issue by jasonmck** [cs340tabyu/cs340Winter2017#564]
If you open up two clients, you can be allowed to have two clients, logged in as the same user, in the same game.

**Comment by jasonmck** [comment]
P3

**Comment by lastmjs** [comment]
@jasonmck Do you mean that if logged in as Sam for example, from two clients, that there are two Sams in the game?

**Comment by intcreator** [comment]
I tried this and both clients just mirror each other.  I figure it's like if I logged into Gmail or Amazon in two places—it's okay to have two clients logged in at the same time as long as everything is consistent between them.

**Comment by dansteren** [comment]
I would consider this a valid issue if it added you to the game twice. However it does not. I tested this with the TA client and server and it has the same behavior. Additionally, there is nothing in the specs that suggests you need to block joining a game if you are already in it.

I agree that this is not the best behavior, but considering that the functional spec says nothing about this, I don't consider it a valid issue.
