### ISSUE TITLE
Winning the game crashed for the winning player.

### ISSUE THREAD

**Issue by mclements37** [cs340tabyu/cs340Winter2017#568]
![winorange](https://cloud.githubusercontent.com/assets/21322207/20416609/36975ea0-acfd-11e6-82dd-3ae1d5547d09.JPG)

In this situation, player red was at 9 points, gained the largest army putting him at 11 points, thus making the game end and show "You Lose" on the screen for player orange (which is correct behavior).

![redwin](https://cloud.githubusercontent.com/assets/21322207/20416614/38a048ec-acfd-11e6-935a-6b5250d0c3c6.JPG)

The problem appeared, however, on player red's screen. It still showed him as having 9 points, it never said he won, and the game sort of crash/froze. I couldn't click "end turn", and it was pretty much stuck. I can't really count this as a P3 since the gameplay is over at this point. However, it is incorrect behavior of the model not updating for the winning player and letting them know they won.

I had a similar issue when making the game, and the problem for me was because the update manager can't handle a score of 11 when there's only 10 circles to draw the victory stars. A simple if(victoryPoints>10){vicotryPoints = 10}; statement fixed the bug for me on my code. I'm assuming yours is resulting from the same error.

Your code is amazing though! Its kind of annoying how we only get credit if we log bugs so I have to do such desperate tests like this to even find a bug in your code.

**Comment by smithskyler** [comment]
I've fixed this and successfully tested that you can win with more than 10 points.
