### ISSUE TITLE
robbed player name not displayed correctly P5 Team 11

### ISSUE THREAD

**Issue by bryceperkins** [cs340tabyu/cs340Winter2017#578]
![image](https://cloud.githubusercontent.com/assets/6720748/20418342/c108ea3e-ad09-11e6-9a0a-96064c3bbc0b.png)

**Comment by athompson909** [comment]
I don't know if that's an error, I mean, I have a cousin named Null

**Comment by athompson909** [comment]
jk

**Comment by athompson909** [comment]
Could you give me some more details about how you generated the bug, I can't seem to replicate it.  Did you place the robber on an empty hex or the desert?  I've tried doing those things...

**Comment by bryceperkins** [comment]
It seems like it just normally happens. Linux or windows. Haven't tried mac.
