### ISSUE TITLE
Game List doesn't update on other clients after one creates a new game 

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#579]
If one client creates a new game, it appears on their own Game Hub view. However, the other clients don't update their list of games until they create another new game too, log in again, or otherwise get the view to redraw. This means every time you want to join your friend's game, you have to make a new one too. I noticed this issue happening on all 4 clients.

**Comment by smithskyler** [comment]
The TAs agreed that this isn't in the spec. See #425
