### ISSUE TITLE
couldn't play monument during turn in which I bought it

### ISSUE THREAD

**Issue by bryceperkins** [cs340tabyu/cs340Winter2017#580]

**Comment by intcreator** [comment]
You should use labels instead of putting the details in the title.

**Comment by mclements37** [comment]
![image](https://cloud.githubusercontent.com/assets/21322207/20438091/80b1b672-ad73-11e6-9b26-1887c5fe8573.png)

Marking as invalid: You can only play monument cards when you have enough points to win, otherwise, it would let you play them.
