### ISSUE TITLE
SelectColorView doesn't disable unavailable colors - server crashes if duplicate color chosen

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#581]
After clicking to join a game that already has other players joined to it, the SelectColorView modal doesn't show the correct unavailable colors. Hopefully you can see what I mean from the screenshot. This may be related to the error I logged earlier about the GameList not updating between clients. 
![screen shot 2016-11-17 at 9 24 25 pm](https://cloud.githubusercontent.com/assets/21317450/20418618/a347bb62-ad0c-11e6-92f6-b30ba8a23951.png)

**Comment by SierraD012** [comment]
EDIT: After I chose Blue again on the rightmost client above, the server crashed. I've included a screenshot of the stack trace in case that helps. Since this caused a crash, I'm upping the severity level. 
![screen shot 2016-11-17 at 9 30 46 pm](https://cloud.githubusercontent.com/assets/21317450/20418681/2f15a280-ad0d-11e6-9d41-e3f797534a24.png)

**Comment by smithskyler** [comment]
I reproduced this, but the server didn't crash. You're seeing a stack trace on a caught exception. If you pick another color, the game continues just fine and the server handles everything correctly. In fact, this is intended behavior. The server will simply reject the request if you try to pick the same color as someone else. The only time that the color isn't disabled is when multiple people go to the color selector at the same time. The faded-out colours update when you go to join a game, but not while you're in limbo between games.
