### ISSUE TITLE
Add AI not available

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#583]
Can not proceed past the Player Waiting screen.  Adding an AI player is not available so you have to connect with 4 clients.

![ai](https://cloud.githubusercontent.com/assets/161021/20420572/eb9e3b5c-ad1b-11e6-821c-aa4c214b62a9.png)

**Comment by SierraD012** [comment]
Dr. Snell told us in class that implementing the AIs is extra credit only. So yes, you can only start a game if you have 4 real clients.

**Comment by irbishop** [comment]
Feel free to argue it with the TAs.   The spec says we have to implement the addAI call, so it is valid.  You can implement the endpoint without having a fully functional AI.
