### ISSUE TITLE
Rejoining a game does not update colors for others

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#584]
The client for user Test was closed.  I reconnected as the Test user with a different color but it was not updated for Test1

![update-color](https://cloud.githubusercontent.com/assets/161021/20420655/682d0b9e-ad1c-11e6-9cd5-2c14c7aca794.png)

**Comment by intcreator** [comment]
You should use labels instead of putting the details in the title.

**Comment by irbishop** [comment]
I would if the TA's added me as a collaborator.  But after sending my info
3 times during Phase 2 I moved on without it.
