### ISSUE TITLE
Select Brown causes a Null Pointer Exception

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#585]
1. Created a new game.
2. "Re-joined" selected brown as color
3. Null Pointer Exception Generated

![npe](https://cloud.githubusercontent.com/assets/161021/20420767/0e6f02e6-ad1d-11e6-9fa0-439047fef41c.png)

Choosing another color allows you to join, so not a P1 crash because the client and server still work.

**Comment by athompson909** [comment]
but who would ever even want to be brown anyway?

**Comment by athompson909** [comment]
haha jk

**Comment by irbishop** [comment]
racist

**Comment by irbishop** [comment]
kidding ^

**Comment by athompson909** [comment]
hehe
