### ISSUE TITLE
Robber Does not prevent gaining resources

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#586]
When the robber is on a tile it should prevent users from gaining resources.

Blue controls a wood tile with the number 3 - note as well that blue has 0 wood currently
![Wood Tile 3](https://cloud.githubusercontent.com/assets/161021/20421368/a5b046ee-ad20-11e6-9214-caea3e2020ac.png)

The robber is moved to occupy that tile, which should prevent resources from that tile:

![robber3](https://cloud.githubusercontent.com/assets/161021/20421386/c2b24f94-ad20-11e6-866c-0df27f6f047c.png)

A 3 is rolled and Blue gains 2 wood:

![resources2](https://cloud.githubusercontent.com/assets/161021/20421401/dc831106-ad20-11e6-9f48-f88e7ab7dcc2.png)

**Comment by mclements37** [comment]
This is now fixed, thanks!
