### ISSUE TITLE
Double Roll freezes client

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#589]
When a double roll is triggered the client that caused it freezes and cannot end their turn or do anything else on the client.

![frozen](https://cloud.githubusercontent.com/assets/161021/20422144/bd0f9df8-ad25-11e6-9ecc-a99db533374b.png)

**Comment by StephBrown923** [comment]
What is a double roll?

**Comment by irbishop** [comment]
Check the screen shots.  The other clients logged the user rolled twice.  The client that rolled twice locked up at that point and could not perform any actions.
