### ISSUE TITLE
The Bar At The Top Is The Color Of Whoever's Turn It Is Currently

### ISSUE THREAD

**Issue by cgrange** [cs340tabyu/cs340Winter2017#598]
The bar at the top should be the same color that the client chose. Yours switches colors to reflect whoever's turn it is currently. You can see this clearly during the set up phase. Here is one picture from after the set up phase that shows Forrest and Azure both have a blue bar up top since that is Azure's color and it is Azure's turn.
![screenshot 57](https://cloud.githubusercontent.com/assets/16614340/20439535/26f3c034-ad79-11e6-8eae-e671616d73d3.png)
![screenshot 58](https://cloud.githubusercontent.com/assets/16614340/20439534/26f268c4-ad79-11e6-801d-6265fde5bdfb.png)
It's possible that this is a p5 instead of a p4. I think it was in the spec though to have the bar reflect the color of the client. I won't be offended if you downgrade this.

**Comment by calvinMcM** [comment]
Not a bug - this is what is supposed to happen according to the spec...

**Comment by calvinMcM** [comment]
That's also a client problem, not a server bug.

**Comment by cgrange** [comment]
If that is what's supposed to happen according to the spec than you're right, it's invalid. However, you are accountable for both client and server problems at this point, which the professor has said over and over again. So it doesn't matter if it's a client problem or a server problem

**Comment by cgrange** [comment]
Many of the other bugs may be client problems but that doesn't make them any less valid
