### ISSUE TITLE
I was able to build a road beyond a settlement even though the settlement was blocking the road's path

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#599]
here's the before and after screenshots (look at the green player towards the bottom right of the screen)
![screen shot 2016-11-18 at 10 29 40 am](https://cloud.githubusercontent.com/assets/16737040/20439707/16f84a0a-ad7a-11e6-9db3-4a410ff9187d.png)
![screen shot 2016-11-18 at 10 29 53 am](https://cloud.githubusercontent.com/assets/16737040/20439708/170d3e9c-ad7a-11e6-9868-e513dbee2fc0.png)

**Comment by athompson909** [comment]
I later tried to build a settlement beyond it and it didn't let me so I don't know if that implies that half the functionality was involved in this
![screen shot 2016-11-18 at 10 37 03 am](https://cloud.githubusercontent.com/assets/16737040/20439980/465bad54-ad7b-11e6-903e-f4715b0ad47a.png)

**Comment by athompson909** [comment]
![screen shot 2016-11-18 at 10 37 03 am](https://cloud.githubusercontent.com/assets/16737040/20439980/465bad54-ad7b-11e6-903e-f4715b0ad47a.png)

**Comment by smithskyler** [comment]
The first issue mentioned here is actually valid according to the game rules (you are allowed to play roads past opposing settlements). The second bug mentioned here is also mentioned somewhere else, so I'll just call this one invalid.
