### ISSUE TITLE
Team 7 - P2 - After Rolling client freezes

### ISSUE THREAD

**Issue by tsmith1644** [cs340tabyu/cs340Winter2017#6]
Explain setup to bug:
1. Login
2. Create new game
3. Add 3 AI's
4. Setup Rounds completed
5. I was the first player and rolled. After seeing the roll value the client freezes and won't do anything else. (Suspected null pointer)
(Exiting the client and reentering the same game allows gameplay to continue)

**Comment by tsmith1644** [comment]
Occurred again well into playing the game

**Comment by cojoco** [comment]
Duplicate of #130 (even though this came first, I pointed the other duplicates to #130 .

**Comment by cojoco** [comment]
This appears to be fixed now.
