### ISSUE TITLE
Unable to build road

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#602]
I don't know if it this is related to #599 or not but the game won't let me build a road (or a settlement) even though it is my turn and I have enough resources
![screen shot 2016-11-18 at 10 42 13 am](https://cloud.githubusercontent.com/assets/16737040/20440079/b35dcee6-ad7b-11e6-8e04-af04d83ff3d7.png)

**Comment by athompson909** [comment]
![screen shot 2016-11-18 at 10 42 44 am](https://cloud.githubusercontent.com/assets/16737040/20440091/c57301b4-ad7b-11e6-8d55-a283e9726cc6.png)

**Comment by athompson909** [comment]
On the next turn I was magically allowed to place a road
![screen shot 2016-11-18 at 10 45 23 am](https://cloud.githubusercontent.com/assets/16737040/20440187/334fc398-ad7c-11e6-8dcb-9556ea7d4242.png)

**Comment by athompson909** [comment]
This issued occured again with player 4 (yellow)
![screen shot 2016-11-18 at 11 00 15 am](https://cloud.githubusercontent.com/assets/16737040/20440674/47558236-ad7e-11e6-9f09-302f95e3adfa.png)

**Comment by athompson909** [comment]
but then on the next turn I was allowed to build a road

**Comment by smithskyler** [comment]
I trust you, but I can't replicate this. Do you have any more details on what you did before this bug happened?
