### ISSUE TITLE
Able to play a development card on the same round that I bought it

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#604]
I bought two development cards (they both ended up being soldiers (I had ended up buying a monument in a previous turn)) and for some reason they were shown as enabled when I initialized the dev card view
![screen shot 2016-11-18 at 10 52 01 am](https://cloud.githubusercontent.com/assets/16737040/20440434/48948d82-ad7d-11e6-8906-15518657fa02.png)

**Comment by athompson909** [comment]
I then tried to use one of the cards and I was allowed to move the robber and then rob a player (in the same turn I bought the card), after that, the development card overlay looked like this:
![screen shot 2016-11-18 at 10 56 02 am](https://cloud.githubusercontent.com/assets/16737040/20440505/a18dba3a-ad7d-11e6-88b9-254d406da42a.png)
I think the error has to do with buying two development cards in the same turn

**Comment by smithskyler** [comment]
I tried to replicate this, but wasn't able to. I bought a dev card on one turn (luckily, it was a monument, just like you), then on the next turn I bought 2 development cards, but I was only able to play the monument. Is there anything else that you did on your turn that might have messed with something (had you seen some other bug in that game, for example)?

**Comment by athompson909** [comment]
were both of the cards soldiers the second time you bought them?
