### ISSUE TITLE
Player Name is prepended to chat messages

### ISSUE THREAD

**Issue by cojoco** [cs340tabyu/cs340Winter2017#605]
When a chat message is written, the player's name is prepended to the text in a way that makes it look like part of the message. In the example picture, the name is "test3" and the message is "Hey". There should be a colon or something to indicate that test3 is the name of the player sending the message.

![uglychatmessage](https://cloud.githubusercontent.com/assets/12629605/20441128/6f5b9502-ad80-11e6-9e77-cb6079095256.png)

**Comment by UnoriginalElephant** [comment]
verified
