### ISSUE TITLE
Robber does not move when a soldier card is played

### ISSUE THREAD

**Issue by cojoco** [cs340tabyu/cs340Winter2017#607]
When a soldier card is played, the robber appears to move to the selected spot, the player who played the soldier card is given the option of people there to rob, but after the player who played the soldier card picks who to rob and gets their resource, the robber moves back to the spot it was at before the soldier card was played.

**Comment by tkatuka** [comment]
This also prevents a player from winning the largest army card.

**Comment by UnoriginalElephant** [comment]
verified that robbing a player with a soldier moves the robber back to the desert

does not hinder getting largest army

**Comment by UnoriginalElephant** [comment]
fixed by hitchcock
