### ISSUE TITLE
Monument card is not usable as soon as it is bought

### ISSUE THREAD

**Issue by cojoco** [cs340tabyu/cs340Winter2017#608]
It says in the functional spec that "Monument cards can be used immediately," but I was unable to use the monument card I'd bought on the same round I bought it, as seen in the image below. I had not played any other dev card with this player during this turn.

![monumentunusableafterbuy](https://cloud.githubusercontent.com/assets/12629605/20441573/5a01245e-ad82-11e6-9027-9424cc346ac5.png)

**Comment by cojoco** [comment]
I was unable to use my monument card even the round after I'd bought it.

**Comment by UnoriginalElephant** [comment]
You're not supposed to be able to play monuments unless you have enough to get to 10 points

**Comment by cojoco** [comment]
It said that in the game rules, but in the functional spec it said you should be able to play them immediately. I'd talk to the TA about it when you're passing off.
