### ISSUE TITLE
Rolling Doesn't Update Resources For All Players

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#609]
After the first and second rounds of the game, I rolled a 6 on one client and it should have updated the wood count of one of the other clients I had active and it didn't. Seems to only update resources for the client who rolled the number.

**Comment by UnoriginalElephant** [comment]
Could you elaborate on how this happened?  I'm testing it and this seems to work just fine.

**Comment by wfearn** [comment]
Was after going from second round to playing states. I rolled a number that
should have given me a wheat and only had 1 wheat (The one gained from
second round). So maybe its the second round that isn't working. If you
can't find it no big deal, I'm just reporting what I thought I saw.

**Comment by UnoriginalElephant** [comment]
Thanks!  I was just wondering if there was a specific set of circumstances behind this.  I haven't been able to reproduce this, which is great :)
