### ISSUE TITLE
Robber does not stop resources from being given on dice roll

### ISSUE THREAD

**Issue by cojoco** [cs340tabyu/cs340Winter2017#611]
In the image below, blue just rolled a 4 and got 2 wood because they had a city next to the wood hex with 4 on it. The robber is on the wood hex with 4 on it, so the resources should not have been given.

![robbernotstoppingresources](https://cloud.githubusercontent.com/assets/12629605/20442045/45655f7c-ad84-11e6-9b37-44ff426ad5d0.png)

**Comment by UnoriginalElephant** [comment]
#612
