### ISSUE TITLE
Game Does Not Declare Winner

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#614]
After winning the game (Reaching 10 victory points before the other players), it said I lost and that someone named "Ender Wiggin" was the winner.

**Comment by UnoriginalElephant** [comment]
What did you do to get to 10 points?  This will help us isolate the bug.  Thanks!

**Comment by wfearn** [comment]
Built two cities when I had 8. Does that answer your question?

**Comment by UnoriginalElephant** [comment]
Yep, thanks!

**Comment by UnoriginalElephant** [comment]
Was this with the default game or one you created?

**Comment by tkatuka** [comment]
Here is a picture. The red player got 10 points and is the winner of the game but it displays the YOU LOSE template for him.
![screen shot 2016-11-18 at 1 51 01 pm](https://cloud.githubusercontent.com/assets/20098554/20446320/3f9d743c-ad96-11e6-86dc-199992b01713.png)
