### ISSUE TITLE
Placing road in first round not working

### ISSUE THREAD

**Issue by kaiboy94** [cs340tabyu/cs340Winter2017#616]
After player 1 placed a road, the overlay closed and then nothing happened.  This happened when I was playing the game as the same player on two different clients.  This is because you allow a player to login multiple times

**Comment by kupiakos** [comment]
Reproduced

**Comment by xandroxygen** [comment]
This error also occurs on the demo client - which also allows you to login multiple times.

**Comment by kupiakos** [comment]
Does it do it with the demo client and server? If it doesn't, then it's a problem with your server.

**Comment by xandroxygen** [comment]
Yes demo client _and_ demo server, thanks.

**Comment by kupiakos** [comment]
I agree this is not a P2, but just because it's in the demo doesn't mean it's an invalid issue.
