### ISSUE TITLE
Can't build road in appropriate location

### ISSUE THREAD

**Issue by ghost** [cs340tabyu/cs340Winter2017#622]
I can't place a road where I should be able to, as seen in the picture below.

I think it's just a weird edge case; every other location I've tested is working as expected.

![invalid place road](https://cloud.githubusercontent.com/assets/22104776/20443139/de7f1302-ad88-11e6-93de-4d015d5abf2d.PNG)

**Comment by csydvs** [comment]
I can't seem to replicate this issue. Here I am building up to another player's settlement:
![image](https://cloud.githubusercontent.com/assets/15003465/20512758/aa1cfdb4-b03e-11e6-8c1d-e9ef9adff51c.png)

And here I am trying to build in that same spot:
![image](https://cloud.githubusercontent.com/assets/15003465/20512770/cbf2952a-b03e-11e6-8555-43885b924015.png)

It must have been wrapped up in one of our other bugs, or something.

**Comment by ghost** [comment]
Yeah, I actually only encountered this bug once; I never had any issues with road buildings as I was doing other testing, so you're probably right that some other bug caused it.
