### ISSUE TITLE
Client color did not update when I logged out and back in

### ISSUE THREAD

**Issue by StephBrown923** [cs340tabyu/cs340Winter2017#623]
![screen shot 2016-11-18 at 12 14 35 pm](https://cloud.githubusercontent.com/assets/16596998/20443261/5f59d9a8-ad89-11e6-94f9-594c2ceffc05.png)

**Comment by smithskyler** [comment]
This is P5 at worst, since it's just the top bar. Everything else looks to have changed color appropriately.
