### ISSUE TITLE
Robbing not fully working

### ISSUE THREAD

**Issue by kaiboy94** [cs340tabyu/cs340Winter2017#625]
I rolled a 7 three times before the robbing actually worked.  Might be because nobody had anything to discard until the third time, but it didn't let me move the robber the other two times.

**Comment by phhorton** [comment]
Confirmed by Philip.  The robber moving and the robbing only works when at least one player has to discard.  If none have to discard, then the robber moving and the robbing are also skipped.

**Comment by sarahkatherine** [comment]
Confirmed by Sarah
