### ISSUE TITLE
Can't set client host or port

### ISSUE THREAD

**Issue by lastmjs** [cs340tabyu/cs340Winter2017#626]
We can't connect to a server that is not localhost. The host is not being set properly from the commandline. We also cannot set the port.

**Comment by intcreator** [comment]
This means we can't play a multiplayer game, so hopefully your AI is working

**Comment by intcreator** [comment]
Actually I've gotten around the multiplayer game by just creating four clients on my own machine
-___-

**Comment by daviscodesbugs** [comment]
Internal Note: Server can now take a port argument: `ant our-server -Dport <port>`

**Comment by daviscodesbugs** [comment]
Internal Note: Client can now take a port argument: `ant our-client -Dport <port>`

**Comment by daviscodesbugs** [comment]
Internal Note: Client can now take a port argument: `ant our-client -Dhost <host>`
