### ISSUE TITLE
Domestic trade doesn't actually trade

### ISSUE THREAD

**Issue by MCTWalker** [cs340tabyu/cs340Winter2017#628]
When the domestic trade modal came up, I was able to select the resources I wanted to trade and the person to trade with. When I clicked trade, nothing happened and the modal just closed.

**Comment by MCTWalker** [comment]
Team 15 P3

**Comment by intcreator** [comment]
You should add labels to this issue instead of a comment with that information.

**Comment by ghost** [comment]
The TAs haven't added her as a collaborator yet, so she can't. Please, don't worry about us, we know what we're doing.

**Comment by csydvs** [comment]
See #627
