### ISSUE TITLE
Can't send domestic trade

### ISSUE THREAD

**Issue by kaiboy94** [cs340tabyu/cs340Winter2017#629]
After picking trade resources, and picking a player to trade with, the trade button appears, but clicking it doesn't do anything.

**Comment by phhorton** [comment]
Confirmed by Philip.  It does not matter if the requested resources are possible for the player to give or not.  The Trade button does not do anything when clicked

**Comment by kupiakos** [comment]
Reproduced by Kevin. However, the trade offer goes through if the clients are restarted and rejoin the game.
