### ISSUE TITLE
I wasn't able to rob a player when I placed the robber back on the desert hex and the player's settlement was next to the desert hex

### ISSUE THREAD

**Issue by MCTWalker** [cs340tabyu/cs340Winter2017#631]
![image](https://cloud.githubusercontent.com/assets/16448612/20443484/3c77273c-ad8a-11e6-8c33-215b1bd03232.png)

**Comment by MCTWalker** [comment]
Team15 P3

**Comment by MCTWalker** [comment]
It's actually not allowing me to rob a player in multiple places where I should be able to...

![image](https://cloud.githubusercontent.com/assets/16448612/20443634/dc1c6ce8-ad8a-11e6-86d0-2d69f7a58c93.png)

![image](https://cloud.githubusercontent.com/assets/16448612/20443658/f44110c6-ad8a-11e6-9b96-8b71cae3def4.png)

**Comment by csydvs** [comment]
I haven't been able to duplicate this, but I bet it has to do with #538 and other bugs in Resource collection. The logic for this is that if the person you were next to had no resources, then you wouldn't be able to rob them. Evidence can be found in the fact that you had recently rolled 7's on all of these examples.
