### ISSUE TITLE
Resource collection is incorrect

### ISSUE THREAD

**Issue by ghost** [cs340tabyu/cs340Winter2017#641]
Resources are not given correctly after a dice roll. I previously had 2/1/1/1/0 resources, and rolling an 8 should have given me no resources as orange, but I was given a wood and sheep.

![incorrectresources](https://cloud.githubusercontent.com/assets/22104776/20443726/4647fb46-ad8b-11e6-9beb-a5a3310ad4f2.PNG)

**Comment by csydvs** [comment]
See #540, part of same resource issue
