### ISSUE TITLE
Game state blocking gameplay?

### ISSUE THREAD

**Issue by michaelpratt28** [cs340tabyu/cs340Winter2017#643]
After player 1 (michael) placed a road and a settlement, the game state apparently changed and is not allowing player 2 (kenneth) to place a road and settlement. Says "Waiting for other players".
<img width="1678" alt="screen shot 2016-11-18 at 12 32 59 pm" src="https://cloud.githubusercontent.com/assets/15473604/20443758/6cf57c82-ad8b-11e6-8289-f9a569b47219.png">

**Comment by irbishop** [comment]
Was this a result of a concurrentmodification exception in the view?

**Comment by michaelpratt28** [comment]
Looks like it's the same issue as #569. Not sure about the concurrentmodification exception.

**Comment by irbishop** [comment]
Thanks
