### ISSUE TITLE
Maritime trade with settlement at port

### ISSUE THREAD

**Issue by kaiboy94** [cs340tabyu/cs340Winter2017#644]
When I build a settlement on a specialized resource port, maritime trade doesn't let me trade even though I have two of a resource to trade for a sheep.  So it's a ratio problem.

*update:  I tried maritime trading when I had 4 wheat, and maritime trade still wanted 4:1 even though the sheep port should've given me 2:1

**Comment by phhorton** [comment]
Update by Philip: The wood specialized resource port allowed me to trade 2 wood for 1 wheat.  It may be the port are different?
