### ISSUE TITLE
Players are not assigned default resources

### ISSUE THREAD

**Issue by kalebo** [cs340tabyu/cs340Winter2017#650]
This may be because we can't get past the first setup turn but ideally the player should see what they have available as they are playing their first two turns.

**Comment by intcreator** [comment]
Players don't get resources until after the first two rounds of setup.  The initial resources are gained from the second settlement each player places as per the game spec:

> Each player receives his starting resources immediately after building his second settlement; for each terrain hex adjacent to this second settlement, he takes a corresponding ResourceCard from the supply

**Comment by dansteren** [comment]
I think this is all working. I'm having a hard time testing right now because we have other things breaking, but the logic should be there as of commit [535dad7](https://github.com/alexandergunnarson/islander-monad/commit/535dad70e89be6df434a65fbcc896409cf685329).
