### ISSUE TITLE
No Victory Points

### ISSUE THREAD

**Issue by taetem** [cs340tabyu/cs340Winter2017#662]
After placing a road and settlement, no victory points are shown. This makes it so no one can ever win.

**Comment by lastmjs** [comment]
- [x] largest army - 2 victory points, remove 2 victory points from the player who had the card before
- [x] longest road - 2 victory points, remove 2 victory points from the player who had the card before
- [x] build settlement - 1 victory point
- [x] build city - 2 victory points
- [x] When a player has 10 or more victory points on their turn, they win!
