### ISSUE TITLE
Cannot play development cards

### ISSUE THREAD

**Issue by Napper15** [cs340tabyu/cs340Winter2017#664]
Cannot play development cards at any point in the game

**Comment by klew91** [comment]
I didn't change any code and playing development cards works fine for me. I bought a bunch of cards and I was always able to play them on my next turn.

**Comment by klew91** [comment]
It turns out that player 1 could always buy and use dev cards, while the other players couldn't. This is because the finish turn command wasn't working properly and was changing the info for only player 1. It is fixed now
