### ISSUE TITLE
Robbing no one still says someone was robbed

### ISSUE THREAD

**Issue by wiseman5** [cs340tabyu/cs340Winter2017#671]
The game history says someone was robbed even though no one was.

<img width="531" alt="no rob" src="https://cloud.githubusercontent.com/assets/16614336/20444446/5807b7c4-ad8e-11e6-9c7f-066dcbf3b0b3.PNG">

**Comment by smithskyler** [comment]
Haha, since we get to choose what the logs say, this definitely isn't a bug. We could very easily have said something like "Someone moved the robber," but we wanted to add some extra personality.
