### ISSUE TITLE
Doesn't Allow Legal Road Placement

### ISSUE THREAD

**Issue by gauntc** [cs340tabyu/cs340Winter2017#672]
![canplaceroad](https://cloud.githubusercontent.com/assets/18722665/20444455/6362d766-ad8e-11e6-8f97-d884aaee77bb.png)

**Comment by irbishop** [comment]
In the setup round you are not allow to place a road there because you would have no legal locations for your second settlement.

![attach](https://cloud.githubusercontent.com/assets/161021/20451402/0506a8d2-adb6-11e6-9c5c-1e1b5680cf39.png)
