### ISSUE TITLE
Doesn't Allocate Resources Correctly After First and Second Round

### ISSUE THREAD

**Issue by gauntc** [cs340tabyu/cs340Winter2017#674]
I had placed my settlements in these rounds and only got 1 resource despite having placed both settlements on a 2-hex or 3-hex location (should have a total of 5 resources).

**Comment by irbishop** [comment]
Thanks. Starting resources should be allocated based off the second settlement, no resources gained during first setup round.

![rss](https://cloud.githubusercontent.com/assets/161021/20496828/f3e072ce-afe3-11e6-982f-72d5b226c024.png)
