### ISSUE TITLE
Longest Road - not full algorithm

### ISSUE THREAD

**Issue by wiseman5** [cs340tabyu/cs340Winter2017#681]
This is only a bug if you were intending to implement the full longest road algorithm for extra credit.  It is only looking for most connected roads.  I labeled it as a P5 because it is extra credit to do the whole thing.
<img width="536" alt="most connected roads" src="https://cloud.githubusercontent.com/assets/16614336/20445000/99078536-ad90-11e6-93d6-478bb966ec95.PNG">

**Comment by smithskyler** [comment]
Yup, that's true.
