### ISSUE TITLE
If a player rejoins, the turn tracker color mismatches with the pieces/chat

### ISSUE THREAD

**Issue by Redge-Ballard** [cs340tabyu/cs340Winter2017#690]
Notice in the screen shot the red turn tracker, but the blue messages and pieces.

<img width="1015" alt="screen shot 2016-11-18 at 1 19 07 pm" src="https://cloud.githubusercontent.com/assets/11576966/20445307/c91c3dd8-ad91-11e6-8877-f9be3c363c75.png">

This occurs on the other clients when a player leaves and rejoins.  The player that leaves and rejoins has correct coloring.

**Comment by intcreator** [comment]
The color isn't updated on the robbing modal either.

<img width="1463" alt="screen shot 2016-11-18 at 1 26 58 pm" src="https://cloud.githubusercontent.com/assets/19642312/20445549/c0ea65f8-ad92-11e6-9842-6f961444672f.png">

And the text is borked.  I won't make an issue for that though.
