### ISSUE TITLE
Stuck Robbing 

### ISSUE THREAD

**Issue by jjaywhitaker** [cs340tabyu/cs340Winter2017#692]
Playing against 3 AI's (Really dumb ones). As soon as it was my turn it said I rolled a 7. I clicked ok but it then prompted me to roll (after it already told me I got a 7). After I "rolled" again I was stuck in the robbing state (the finish turn button said "Robbing") but there was no modal for me to rob anyone.

**Comment by jjaywhitaker** [comment]
Changed to a p3 because if you send a chat it somehow makes the rob modal come up

**Comment by Chroniclerz** [comment]
#700 Its caused by the exception of Auto rolling
