### ISSUE TITLE
Player waiting doesn't update properly.

### ISSUE THREAD

**Issue by tylercr2** [cs340tabyu/cs340Winter2017#707]
Joined a game as a human player.
In a 2nd client, joined the same game.
On the 2nd client, added 2 AI, game started.

On player1's screen, it showed them as the only player in the game. When I clicked add AI player, it went into set up phase, and all the players were there. Just not updating on the first players player waiting.

**Comment by Chroniclerz** [comment]
Resolved. I would classify this is p4 or p5 because it didn't affect gameplay
