### ISSUE TITLE
Discarding doesn't always update

### ISSUE THREAD

**Issue by tylercr2** [cs340tabyu/cs340Winter2017#716]
Sometimes discarding doesn't go through. I was in a game with 2 humans, 2 AIs, and it is waiting for 
discard to go through on both humans. It doesn't happen everytime, and it seems to happen if the the automatic rolling occurs and rolls a 7. I've recreated this twice, the first time no one was asked to discard,
the second time, a player discarded and still was waiting. Restarting the client fixes this issue to get past it.

**Comment by Chroniclerz** [comment]
#700 same exception from the automatic rolling
