### ISSUE TITLE
First round setting

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#718]
In a game without AI, player 3 cannot place his settlement after player 2 placed his road. Modal pops up to allow settlement placing after player 3 sends a message.

**Comment by Chroniclerz** [comment]
Could not replicate after various testing. More details as to surrounding events would help.
Tests run:
- Interjected chat messages
-various AI and no AI configurations (Player,Ai,Player,AI ; Player, Player, Player, AI  ; Player, Player, Ai, AI  ; Player Player Player Player ; Player Ai AI Player)
-Various Settlement placement schemas
-Various logging out and logging back in order of operations

**Comment by Chroniclerz** [comment]
Could not replicate after various testing. More details as to surrounding events would help.
Tests run:

Interjected chat messages 
various AI and no AI configurations (Player,Ai,Player,AI ; Player, Player, Player, AI ; Player, Player, Ai, AI ; Player Player Player Player ; Player Ai AI Player) 
Various Settlement placement schemas -Various logging out and logging back in order of operations
