### ISSUE TITLE
There are no AIs

### ISSUE THREAD

**Issue by derbraun** [cs340tabyu/cs340Winter2017#739]
![screenshot from 2016-11-18 14 34 50](https://cloud.githubusercontent.com/assets/21980276/20447458/3224c82c-ad9c-11e6-9fc9-a39832def8f1.png)

**Comment by tylercr2** [comment]
TAs say its not required for phase 3, but is extra credit.

**Comment by derbraun** [comment]
Does that include "Most Roads?"
The specs say that at least "Most roads" is required.

**Comment by jjaywhitaker** [comment]
The "most roads" is required, the "longest road" is not required.

**Comment by tylercr2** [comment]
The most roads you are thinking of is that we are required to implement calculating who has the most roads. The longest road (Properly calculating it instead of just counting who has played the most roads) is extra credit. There is no required AI Type, and most roads is not a required AI type.
