### ISSUE TITLE
Not allowed the option of robbing no one. Forced to rob 3 times

### ISSUE THREAD

**Issue by klew91** [cs340tabyu/cs340Winter2017#741]
The first time I had to rob someone I chose to rob no one. Then I was forced to rob a second time. The second time I chose to rob a hex that had players on it but the modal showed up with no players to rob. Then I finally had to rob a 3rd time and was able to rob someone 

https://gyazo.com/1f83c6819f39cf884d65f7424f2481a6

**Comment by irbishop** [comment]
duplicate of #590
