### ISSUE TITLE
Can not play Monument Card after playing a devCard 

### ISSUE THREAD

**Issue by jbskaggs** [cs340tabyu/cs340Winter2017#750]
1. Create a new game with 4 non-AI players with none of the boxes checked
2. Keep buying devCards with one of the players whenever resources are sufficient 
3. Play Soldier Card
4. Go to play Monument Card durring the same turn(You should be able to but it is disabled)  
![image](https://cloud.githubusercontent.com/assets/22157774/20448077/6449064e-ad9f-11e6-8f6c-066216d7e413.png)

**Comment by mike0256** [comment]
From what I understand of the third paragraph on page 18 of the functional spec you are only allowed to play one development card per turn.

**Comment by jbskaggs** [comment]
That is true with the exception of the monument card you can always play.
