### ISSUE TITLE
server and client both only run on port 8081

### ISSUE THREAD

**Issue by derbraun** [cs340tabyu/cs340Winter2017#751]
In section 6 of Implimentation and Testing, the spec states: Create a command line parameter for the port on your server. Unfortunately, this is not running properly.

![screenshot from 2016-11-18 14 37 10](https://cloud.githubusercontent.com/assets/21980276/20447669/79607974-ad9d-11e6-9aad-bf6fd6a36bb3.png)

 Curious thing, is that when I start the client on port 8888, it finds the server running on 8081.
 I started the demo server on port 8888 and the client can't find it.  

![screenshot from 2016-11-18 14 43 59](https://cloud.githubusercontent.com/assets/21980276/20447929/b2cf5e22-ad9e-11e6-8fa9-d5f11cf84011.png)

The spec from **Phase 2** states: Create command line parameters on your client for both the host and port on which the Catan server is running. Modify the ant target “our-client” to support passing these
parameters into the target with the names “host” and “port” respectively.

So, if this was implemented properly, I should be able to start your client at localhost 8888 and it will find the demo server running on port 8888, which it does not.

Marking as P2 because if you followed phase 2 specs, it would block gameplay.

**Comment by tylercr2** [comment]
Client / Server are curently hard coded, we didn't get to implementing that. Adding reclassification because in its current state, it does not block gameplay, even though it has incorrect behavior. Its missing the ability to change ports / host, but is not blocking gameplay.
