### ISSUE TITLE
Largest Army Not implemented

### ISSUE THREAD

**Issue by jbskaggs** [cs340tabyu/cs340Winter2017#754]
1. create a new game with 4 non-AI players with none of the boxes checked
2. keep buying devCards with one of the players whenever resources are sufficient  
3. play Soldier Card 
4. After playing the Soldier Card 3 times with the same player there is no change in the victory points

**Comment by wfearn** [comment]
Are there any details you might be missing from this? I replicated this process but the victory points were added as needed and the icon appeared signifying largest army. Going to close otherwise.
