### ISSUE TITLE
Infinite settlements in setup round

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#756]
If you close a client and then reopen it during the setup round between placing the settlement and placing the road you are prompted, and allowed, to place another settlement. I desisted after 4 settlements, but it is clearly possible to place as many settlements as the map supports (Even beyond the supposed max 5 owned by one player, since it doesn't detract from the resource count)
![bug18](https://cloud.githubusercontent.com/assets/22157895/20450010/4cb6f788-adaa-11e6-8cfc-a75a4f7a1d7c.png)

**Comment by victorlazaro** [comment]
The TAs code does the same thing, so I'm marking it as invalid.
