### ISSUE TITLE
Starte up resources arent correct

### ISSUE THREAD

**Issue by abatschi** [cs340tabyu/cs340Winter2017#763]
You should only get resources for the hexes the second settlement placed down is touching. The resource bar holds random values for all the players.

**Comment by klew91** [comment]
I think this is a P4, not a P3. This is a pretty obscure rule that I had to go into the Rules Almanac to find, its not even in the specification. The resources are not random, you get resources for the adjacent hexes to settlements built in both rounds, not just the second. Fixing the bug will just be a matter of taking away the resources granted for the settlement built in the first round. This doesn't block gameplay, it just gives you a few more resources than you should get in the setup round.

**Comment by abatschi** [comment]
I checked if it was just giving resources for both settlements and that was not the case. I looked at it with 4 clients and no one fit what you described.
