### ISSUE TITLE
Domestic Trade

### ISSUE THREAD

**Issue by abatschi** [cs340tabyu/cs340Winter2017#764]
the domestic trade arrows dont correlate to what the resource bar says I actually have (dont know which one is wrong). In my example the resource bar says I have an ore but the domestic trade wont let me hit the up arrow to offer the ore.

**Comment by abatschi** [comment]
Oh nevermind the issue is that you cant say I'm going to send 2 different resources. But this is also an issue

**Comment by gauntc** [comment]
I couldn't find anywhere in the spec that requires us to be able to send multiple resource types.
