### ISSUE TITLE
Wrong starting resources (or wrong after first roll)

### ISSUE THREAD

**Issue by bmarker6** [cs340tabyu/cs340Winter2017#769]
When I rolled for the first time, I rolled a 6 and realized the resources were off. This was either from getting resources at the start of the game or the rolling gave out resources incorrectly.

<img width="1280" alt="screen shot 2016-11-18 at 4 56 37 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451162/a0f49e82-adb3-11e6-9b25-5d36ffafa501.png">
<img width="1280" alt="screen shot 2016-11-18 at 4 57 12 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451163/a1cb7862-adb3-11e6-85e4-975180284fca.png">

**Comment by csydvs** [comment]
See #641
