### ISSUE TITLE
Domestic Trade does not work

### ISSUE THREAD

**Issue by bmarker6** [cs340tabyu/cs340Winter2017#770]
Every time I try a domestic  trade, it gets rejected without going to the receiving player. The chat says the trade was rejected by AI, even though no AI are in the game.

<img width="1280" alt="screen shot 2016-11-18 at 5 02 32 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451185/e1f70366-adb3-11e6-8a14-1d12631a3243.png">
<img width="1280" alt="screen shot 2016-11-18 at 5 02 34 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451186/e33932da-adb3-11e6-9088-57fad7f3c50b.png">
<img width="1280" alt="screen shot 2016-11-18 at 5 02 12 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451207/17af961c-adb4-11e6-9deb-a8c3158a251d.png">

**Comment by csydvs** [comment]
See #536
