### ISSUE TITLE
Every player lost all resources, presumably after robbing.

### ISSUE THREAD

**Issue by bmarker6** [cs340tabyu/cs340Winter2017#773]
After I robbed a hex where no one was at, I noticed all players had 0 resources.

<img width="1280" alt="screen shot 2016-11-18 at 5 05 16 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451229/56d08996-adb4-11e6-924b-059af2cb2e32.png">
<img width="1280" alt="screen shot 2016-11-18 at 5 05 18 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451230/58023ce2-adb4-11e6-851a-f79a68d146e3.png">
<img width="1280" alt="screen shot 2016-11-18 at 5 05 20 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451232/58f348c6-adb4-11e6-8a5f-0a93bf58fe72.png">
<img width="1280" alt="screen shot 2016-11-18 at 5 05 22 pm" src="https://cloud.githubusercontent.com/assets/15066765/20451235/59a63526-adb4-11e6-8792-0e9cd4acaac8.png">

**Comment by csydvs** [comment]
See issue #538
