### ISSUE TITLE
Discarding doesn't log a message

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#779]
On the rare chance your game survives discarding (1 in 7 or so) when you discard it doesn't leave a log message.
![bug23](https://cloud.githubusercontent.com/assets/22157895/20451403/055e321e-adb6-11e6-8f71-8ab906b99d3c.png)

**Comment by victorlazaro** [comment]
The TAs client also doesn't have a discard message, so I'm marking this as invalid.
