### ISSUE TITLE
Could not rob from player after placing robber

### ISSUE THREAD

**Issue by spencerolsen** [cs340tabyu/cs340Winter2017#787]
I looked up the rules to see if I understand right, but I believe that in the screenshot below I should have been able to rob orange player 'bbb'. After placing the robber where it is shown, the modal popped up to ask who I want to rob, but it only had the "None" option, and I couldn't rob player bbb.

![2016-11-18 3](https://cloud.githubusercontent.com/assets/3418771/20452717/1d9c9ede-adce-11e6-9a05-9ac711bd6bc8.png)

**Comment by cojoco** [comment]
Did you ensure that the orange player had resources? You can't rob from a player that has no resources.

**Comment by spencerolsen** [comment]
Yes, the orange player had resources.
