### ISSUE TITLE
Moving robber blocks gameplay (Phase 3, Group 6, P2)

### ISSUE THREAD

**Issue by johnlarson** [cs340tabyu/cs340Winter2017#794]
Steps to reproduce:

1. Play until you roll a seven.
2. When prompted, move the robber. I moved it to a spot with no one to rob; I don't know if that detail matters or not.
3. The robber will remain on the desert hex, and when click the "End Turn" button, it greys out and the text on it switches to "Waiting for other Players". However, after some amount of time, sometime no time, sometimes after a sec, it goes back to "End Turn". No matter how many times you click it, it keeps going back to "End Turn". All the other players are in the "Waiting for other Players" state.

**Comment by tylercr2** [comment]
The detail on no one to rob was very helpful. We weren't checking to see if no one was being robbed on the server, and then we were accessing an object out of range, and so it would cause everything to get stuck.
