### ISSUE TITLE
Two Robbers

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#795]
When you are choosing where to place the robber it looks like there are suddenly two robbers because you don't fade out the currently placed robber:
![doublerobber](https://cloud.githubusercontent.com/assets/5455419/20453065/42cf8c26-add7-11e6-90a5-7a536f2881d4.png)
The robber should either be faded out (like it is in the functional spec) or it should be removed and you should just display a "no" icon over it's current location.
Functional Spec Example:
![robberfade](https://cloud.githubusercontent.com/assets/5455419/20453085/e28fada4-add7-11e6-820f-f370f98d41eb.png)

## Setup:
**Players:** 4 humans, 0 AIs
**Phase:** Normal Gameplay
**Turn Status:** Robbing

**Comment by Napper15** [comment]
I am marking this as invalid because 1. it doesn't do this in the demo client.   2. It is coded this way in the UI code.
