### ISSUE TITLE
[Team 6][Phase 3][P4] Adjacent High-Value Hexes

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#800]
The random numbers option creates maps that have "8" hexes and "6" hexes next to each other.
<img width="221" alt="adjacent_high_values" src="https://cloud.githubusercontent.com/assets/21351700/20453203/ffd0bd20-add9-11e6-81f7-b67bc786f82a.png">

**Comment by tylercr2** [comment]
TA's said this is not a requirement.
