### ISSUE TITLE
[Team 6][Phase 3][P2] Not Able to End Turn After Robbing Empty Hex

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#801]
After robbing an empty hex, an error is thrown and I can't finish my turn until I log out, log in, and select a new hex that has a player adjacent to it.  
<img width="480" alt="robber_loop" src="https://cloud.githubusercontent.com/assets/21351700/20453214/34e983fc-adda-11e6-9f33-4055ad61a8fa.png">
<img width="427" alt="robber_loop_2" src="https://cloud.githubusercontent.com/assets/21351700/20453216/34ecfdac-adda-11e6-942d-24c544c80f7a.png">
<img width="470" alt="robber_loop_3" src="https://cloud.githubusercontent.com/assets/21351700/20453217/34ed9640-adda-11e6-9d16-4e1b5fd61e54.png">
<img width="478" alt="robber_loop_4" src="https://cloud.githubusercontent.com/assets/21351700/20453218/34ee8e06-adda-11e6-910d-8ec4f8680d70.png">

**Comment by tylercr2** [comment]
#794
