### ISSUE TITLE
[Team 6][Phase 3][P3] Able to Rob Self

### ISSUE THREAD

**Issue by dannya951** [cs340tabyu/cs340Winter2017#802]
I'm able to rob myself.  The log reflects this in the messages, even though my net resources don't change.  
<img width="483" alt="rob_self" src="https://cloud.githubusercontent.com/assets/21351700/20453233/874590be-adda-11e6-8266-1a9a890937a6.png">
<img width="116" alt="rob_self_2" src="https://cloud.githubusercontent.com/assets/21351700/20453232/8745390c-adda-11e6-87f7-099e35ed1263.png">

**Comment by Rocker398** [comment]
able to reproduce
