### ISSUE TITLE
Cannot rejoin game after failed registration

### ISSUE THREAD

**Issue by kupiakos** [cs340tabyu/cs340Winter2017#807]
1. Register a new user "bob" and start a new game.
2. Fill the game with 3 other players so the game starts.
3. Stop the "bob" client.
4. Start another client.
5. In that client, attempt to register as the username "bob" again.
6. The registration will fail, as expected. Note: "Invalid username/password" is not very helpful.
7. Now, log in correctly as "bob".
8. The game that should be rejoinable simply says "Full". If step 2 hadn't been performed, it would just say "Join" but would still work when clicked.

**Comment by phhorton** [comment]
Confirmed by Philip.  I closed the clients and when I logged in, I could not re-join the game.
