### ISSUE TITLE
Joining a game

### ISSUE THREAD

**Issue by sarahkatherine** [cs340tabyu/cs340Winter2017#808]
One client yoyoyo can create a game and not join it and the welcome to the game hub page for that same client yoyoyo will say that the client yoyoyo is in the game that was created and at the same time have the choice of re-joining the game.

If you add a different client hihihi to the game, the waiting for players modal will say it needs two more players and only display yoyoyo and not hihihi

At this point, if yoyoyo actually joins the game, hihihi's client does not update to display yoyoyo's name.

**Comment by xandroxygen** [comment]
When you create a game, the client auto-joins you into that game, because the demo client does this as well. 

I followed your steps and was unable to reproduce the problem - the waiting for players list on both clients was always up to date.
