### ISSUE TITLE
Unable to point client to a different server

### ISSUE THREAD

**Issue by ringmaster217** [cs340tabyu/cs340Winter2017#810]
I tried running a server remotely so that we could play together, and I ran the client using java -jar client.jar 192.168.1.239, but the client never connected to the server even though it says Setting host to 192.168.1.239.

I'm marking this as a p4 because it's not actually part of the gameplay, but it is in the spec for phase 2.

**Comment by csydvs** [comment]
It's true that that wouldn't work that way, we implemented this with a different command line argument, but the TAs don't give those instructions to the implementing group.
