### ISSUE TITLE
Welcome to the Game Hub

### ISSUE THREAD

**Issue by sarahkatherine** [cs340tabyu/cs340Winter2017#811]
If I open four catan clients (yoyoyo, hihihi, sleepy, work) and add each one to a game, and I add a fifth catan client and log in as yoyoyo, the Welcome to the Game Hub page shows that I can "re-join" that game that it shows that I (yoyoyo) am already in... but when I press re-join I cannot rejoin.

**Comment by xandroxygen** [comment]
Unable to reproduce this - when I log in as a player who is already logged in, it lets me rejoin the game and take control.
