### ISSUE TITLE
set-up round

### ISSUE THREAD

**Issue by sarahkatherine** [cs340tabyu/cs340Winter2017#813]
In the set-up round, the player is supposed to put down a settlement first and then a road, not a road and then a settlement.

**Comment by spencerolsen** [comment]
From the functional specs it says (in the Setup section on page 7): 

On a player’s turn, the “place road” overlay should appear. When a player places a road, it should close
the modal and update the map. Then the “place settlement” overlay should appear; when placed, the
overlay should disappear and the map should update. Then the player’s turn should end. These should
happen automatically.
