### ISSUE TITLE
Modals don't clear on exit

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#816]
There are multiple modals that you don't clear when you exit

- Create Game Modal
- Domestic Trade Modal
-  Probably Maritime Trade if I could get it to work.

I think these modals should be cleared when you close them. Otherwise, you could enter some data, close the modal, go a few turns and open it back up and it would have the old data in there. I don't think that's the standard behavior in apps.

**Comment by cgrange** [comment]
I fixed the Create Game Modal so that it clears on exit the other two I tested and they seem to be working just fine. They worked fine during the client phase also and we didn't change them so I don't know how he got them to not clear on exit but they seem to be working now
