### ISSUE TITLE
Destination Cards on Startup

### ISSUE THREAD

**Issue by chaselundell** [cs340tabyu/cs340Winter2017#825]
after starting a game I chose 3 destination cards. When I went to view them in the slide out I had three of the same card.(boston to Miami) This only happened on startup.
![image](https://cloud.githubusercontent.com/assets/12955234/24470728/2dabf318-147d-11e7-9ca4-91368635528a.png)

**Comment by alexanderboswell** [comment]
So if we have fixed this bug before we have even given you a final version of our project, does it even count?

**Comment by chaselundell** [comment]
ya I'll just try it again tomorrow and I'll just remove the issue if I don't see it since we all have till 12 tonight.

**Comment by alexanderboswell** [comment]
This was fixed before the final version was actually given to the other group.
