### ISSUE TITLE
2 links between 2 cities

### ISSUE THREAD

**Issue by alexanderboswell** [cs340tabyu/cs340Winter2017#832]
When there are two spots to play between two cities, one can be claimed by one player but the other can not be claimed by anyone. Example : client on the right has claimed a route between Montreal and Boston. Client on the left can not claim the other spot from Montreal to Boston.
<img width="1167" alt="screen shot 2017-03-29 at 9 26 02 pm" src="https://cloud.githubusercontent.com/assets/21343215/24486280/8c1b7e48-14c6-11e7-8d5e-2a441a2986ad.png">

**Comment by trevorlyman** [comment]
This is the correct behavior. When there is three or less player in ticket to ride all double routes act as single routes.
