### ISSUE TITLE
Should be able to draw all 3 destination cards at the begining

### ISSUE THREAD

**Issue by ribsalad** [cs340tabyu/cs340Winter2017#853]
If you click nothing on the initial turn except return destination card it automatically chose one to return (you end up with two cards). You should be able to return none. Additionally, if you click one to return and then want to deselect it to return only none, it should allow that.

**Comment by tjacobhi** [comment]
Isn't there a button to the right that is to "keep all cards"?

**Comment by ribsalad** [comment]
Maybe? Not visible on mine but that could be a screen issue?

**Comment by ribsalad** [comment]
If it is visible to you then I think its fine? I just don't have an emulator I can see it on. Close this if its working for you :)
