### ISSUE TITLE
After I discard the screen freezes

### ISSUE THREAD

**Issue by abatschi** [cs340tabyu/cs340Winter2017#93]
After I discard when a seven is rolled, it takes away the resources correctly but then the screen freezes and I cant do anything...

**Comment by dolson25** [comment]
on a game with 4 real players everyone discards and waits for each other correctly but then 3 players wait for one player, and his screen says "robbing" but the robbing modal is not showing

**Comment by Napper15** [comment]
I just had another problem occur related to this.  Playing with 3 AI, I rolled a 7, moved the robber and then the game froze.

**Comment by Napper15** [comment]
I just had it happen again.  I discarded -> rolled -> game frozen
