### ISSUE TITLE
"You rolled a 7" modal displayed twice

### ISSUE THREAD

**Issue by intcreator** [cs340tabyu/cs340Winter2017#98]
Every time the player rolls a 7, they are shown the "Move the Robber" dialog.  After the player moves the robber, the "You rolled a 7" dialog is shown again.

Because of the weird stack that the GUI uses, it's possible that this modal was simply never closed when the robber modal is shown.

**Comment by smithskyler** [comment]
This isn't a bug.

**Comment by bmarker6** [comment]
Fixed
